"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { useScopeTransition } from "./useScopeTransition";
import type { ActorMode, ApplicantCase, InitiativeDraft, MemberRuntime, Result } from "./types";

const memberNav = [["/member/home","Übersicht"],["/member/membership","Profil & Mitgliedsstatus"],["/member/initiatives","Meine Vorschläge"],["/member/deliberation","Programmwerkstatt"],["/member/delegation","Meine Stimmen & Delegation"],["/member/assurance/authentication-session-assurance","Sicherheit"]] as const;

export function MemberWorkspace({ path, runtime, actor }: { path: string; runtime: MemberRuntime; actor: ActorMode }) {
  const locale = useSearchParams().get("lang") === "en" ? "en" : "de";
  const scope = useScopeTransition(runtime.organizationScope);
  const isApplication = path === "/member/application" || path === "/member/membership/appeal";
  const denied = actor === "applicant" && !isApplication;
  const unavailable = actor === "anonymous" || runtime.profile === "production";
  const logoTarget = actor === "applicant" ? "/member/application" : "/member/home";
  return <div className="app-shell member-shell">
    <a className="skip-link" href="#member-main">Zum Inhalt</a>
    <header className="site-header"><div className="workspace-heading"><Link className="logo" href={`${logoTarget}?lang=${locale}`}>EPD²</Link><span>Bürgerbereich</span></div><div className="header-actions"><Link href={`${path}?lang=de`}>DE</Link><span aria-hidden>·</span><Link href={`${path}?lang=en`}>EN</Link></div></header>
    {!isApplication && actor === "member" && runtime.profile === "fixture" && <nav className="member-navigation" aria-label="Mitgliederbereich">{memberNav.map(([href,label]) => <Link key={href} href={`${href}?lang=${locale}`} aria-current={path===href?"page":undefined}>{label}</Link>)}</nav>}
    <main id="member-main" className="main" tabIndex={-1}>
      {unavailable ? <State title="BLOCKED" text={locale === "en" ? "Responsible runtime is unavailable" : "Verbindung zur zuständigen Laufzeit nicht verfügbar"} help="Nicht akzeptierte Laufzeitfunktionen bleiben fail-closed." /> : denied ? <State title="Zugriff nicht möglich" text={locale === "en" ? "This area is not available to your account." : "Dieser Bereich ist für Ihr Konto nicht freigegeben."} help="Der geschützte Datensatz wird nicht bestätigt oder verneint."><Link className="button button--primary" href={`/member/application?lang=${locale}`}>Zum eigenen Antrag</Link></State> : <RouteContent path={path} runtime={runtime} actor={actor} scope={scope} />}
    </main>
  </div>;
}

function State({title,text,help,children}:{title:string;text:string;help:string;children?:React.ReactNode}) { return <section className="state-panel" role="status"><span className="status-badge">{title}</span><h1>{text}</h1><p>{help}</p>{children}</section>; }
function Page({title,lead}:{title:string;lead:string}) { return <header className="page-header"><div><p className="eyebrow">EPD² · Bürgerbereich</p><h1>{title}</h1><p>{lead}</p></div></header>; }
function Card({title,children}:{title:string;children:React.ReactNode}) { return <section className="card"><h2 className="card-title">{title}</h2>{children}</section>; }
function Capability({status,owner,reason}:{status:string;owner:string;reason:string}) { return <aside className="notice" role="status"><strong>{status}</strong><p>{reason}</p><small>Zuständig: {owner}.</small></aside>; }
function ProgramDraftContext(){return <aside className="notice" role="status"><strong>Grundsatzprogramm – Gründungsfassung 1.2 · Entwurf / noch nicht beschlossen</strong><p>Vorschläge und Beratung sind keine bereits angenommenen Programmpunkte.</p><a href="https://epd-partei.de/programm.html">Öffentlichen Programmstatus ansehen</a></aside>;}
function ProcessChain(){return <section className="card"><h2 className="card-title">Weg eines Programmvorschlags</h2><p>Problem → Strukturierung → Diskussion → Fach-/Rechtsprüfung → demokratische Entscheidung → Dokumentation</p></section>;}

type ScopeState = ReturnType<typeof useScopeTransition>;
function ScopeSelector({scope}:{scope:ScopeState}) { return <section className="scope-control" aria-busy={scope.pending}><label htmlFor="scope">Meine Organisation</label><p className="muted">Bund · Landesverbände · Regional-/Ortsverbände. Angezeigt werden ausschließlich serverseitig autorisierte Umfänge.</p><select id="scope" value={scope.scope} disabled={scope.pending||scope.loadingScopes||scope.scopes.length===0} onChange={(e)=>void scope.transition(e.target.value)}>{scope.scopes.map((candidate)=><option key={candidate.ref} value={candidate.ref}>{candidate.label}</option>)}</select>{scope.loadingScopes&&<span role="status">Autorisierte Organisationen werden geladen.</span>}{scope.pending&&<span role="status">Berechtigung wird neu geprüft; vorherige Inhalte wurden entfernt.</span>}{!scope.contextReady&&!scope.pending&&<span role="alert">Zielumfang nicht aktiviert. Geschützte Inhalte bleiben verborgen.</span>}</section>; }

function useScoped<T>(scope:ScopeState, loader:(scopeRef:string,signal:AbortSignal)=>Promise<Result<T>>) {
  const [data,setData]=useState<T|null>(null); const [error,setError]=useState<string|null>(null); const generation=useRef(0);
  useEffect(()=>{const current=++generation.current;setData(null);setError(null);if(!scope.contextReady||!scope.scope||!scope.contextVersion)return;const c=new AbortController();void loader(scope.scope,c.signal).then((r)=>{if(c.signal.aborted||current!==generation.current)return;if(r.ok)setData(r.value);else setError(r.error.safeMessage);});return()=>c.abort();},[scope.contextReady,scope.scope,scope.contextVersion,loader]);
  return {data,error};
}

function RouteContent({path,runtime,actor,scope}:{path:string;runtime:MemberRuntime;actor:ActorMode;scope:ScopeState}) {
  if(path==="/member/application") return <Applicant runtime={runtime}/>;
  if(path==="/member/membership/appeal") return <><Page title="Rechtsbehelf zur Mitgliedschaft" lead="Ihr eigener Verfahrensweg bleibt in diesem Bereich. Interne Bearbeitung im Compliance- und Rechtsbereich wird nicht geöffnet."/><Capability status="BLOCKED" owner="Mitgliedschaft / Compliance & Recht" reason="Rechtliche und operative Aktivierung ist nicht nachgewiesen."/></>;
  if(actor!=="member") return <State title="UNAVAILABLE" text="Seite nicht verfügbar" help="Der geschützte Datensatz wird nicht bestätigt oder verneint."/>;
  if(path==="/member/home") return <Home runtime={runtime} scope={scope}/>;
  if(path==="/member/membership") return <Membership runtime={runtime} scope={scope}/>;
  if(path==="/member/initiatives") return <Initiatives runtime={runtime} scope={scope}/>;
  if(path==="/member/initiatives/new") return scope.contextReady?<InitiativeFlow runtime={runtime} scopeRef={scope.scope}/>:<State title="LOADING" text="Autorisierte Organisation wird geladen" help="Ein Vorschlag kann erst nach erfolgreicher Scope-Autorisierung vorbereitet werden."/>;
  if(path==="/member/deliberation") return <Deliberation runtime={runtime} scope={scope}/>;
  if(path==="/member/delegation") return <Delegation runtime={runtime} scope={scope}/>;
  if(path==="/member/assurance/authentication-session-assurance") return <><Page title="Anmeldung, Sitzungen & Vertrauensarchitektur" lead="Darstellung der durch API‑02 gelieferten Assurance; keine eigene Authentifizierungsautorität."/><aside className="notice"><strong>eID: geplant, derzeit nicht live</strong><p>Identitätsprüfung und Mitgliedschaftsentscheidung bleiben getrennte Schritte.</p></aside><Capability status="BLOCKED" owner="API‑02" reason="Sitzungs-, Passkey-, Widerrufs- und Recovery-Laufzeit ist bis zur unabhängigen API‑02-Annahme fail-closed."/></>;
  return <State title="UNAVAILABLE" text="Seite nicht verfügbar" help="Der geschützte Datensatz wird nicht bestätigt oder verneint."/>;
}

function Home({runtime,scope}:{runtime:MemberRuntime;scope:ScopeState}){const read=runtime.memberCore.read.bind(runtime.memberCore);const {data,error}=useScoped(scope,read);return <><Page title="Mein Bürgerbereich" lead="Persönliche Mitgliedschaft, eigene Vorschläge und regionale Beteiligung – jeweils nur im serverseitig freigegebenen Organisationsumfang."/><aside className="notice"><strong>Bürgerbereich im Aufbau</strong><p>eID und sichere Online-Abstimmungen werden nicht als live dargestellt.</p></aside><ScopeSelector scope={scope}/>{error&&<Capability status="BLOCKED" owner="MemberCorePort" reason={error}/>} {data&&<><div className="grid"><Card title="Profil & Mitgliedsstatus"><strong>{data.status} · {data.organization}</strong></Card><Card title="Aufgaben"><ul>{data.tasks.map(x=><li key={x}>{x}</li>)}</ul></Card><Card title="Fristen"><ul>{data.deadlines.map(x=><li key={x}>{x}</li>)}</ul></Card><Card title="Mitteilungen"><ul>{data.messages.map(x=><li key={x}>{x}</li>)}</ul></Card><Card title="Abstimmungen"><strong>GEPLANT / NICHT AKTIVIERT</strong><p>Hier wird nur Verfügbarkeit angezeigt; keine Stimmabgabe im Bürgerbereich.</p></Card><Card title="Meine Stimmen & Delegation"><strong>{data.capabilities.delegation}</strong></Card><Card title="Regionale Beteiligung">Autorisierter Umfang: {data.organization}</Card></div><section className="card"><h2 className="card-title">Weitere EPD²-Bereiche</h2><ul><li><a href="https://epd-partei.de/transparenz.html">Transparenz</a></li><li><a href="https://epd-partei.de/transparenz/abgeordnetentisch.html">Offener Abgeordnetentisch</a></li><li><a href="https://epd-partei.de/struktur/digitales-buero.html">Digitale Bürgerbüros</a></li></ul></section></>}</>;}
function Membership({runtime,scope}:{runtime:MemberRuntime;scope:ScopeState}){const read=runtime.membership.read.bind(runtime.membership);const {data,error}=useScoped(scope,read);return <><Page title="Profil & Mitgliedsstatus" lead="Identitätsprüfung allein aktiviert keine Mitgliedschaft."/><ScopeSelector scope={scope}/>{error&&<Capability status="BLOCKED" owner="MembershipPort" reason={error}/>} {data&&<><dl className="record"><dt>Status</dt><dd>{data.status}</dd><dt>Zuordnung</dt><dd>{data.affiliation}</dd><dt>Version</dt><dd>{data.version}</dd><dt>Provenienz</dt><dd>{data.provenance}</dd><dt>Entscheidung</dt><dd>{data.decisionState}</dd><dt>Dokumentstatus</dt><dd>{data.documentState}</dd></dl><h2>Verlauf</h2><ol className="timeline">{data.history.map(x=><li key={x}>{x}</li>)}</ol><Link className="button button--secondary" href="/member/membership/appeal">Korrektur oder Rechtsbehelf</Link></>}</>;}
function Initiatives({runtime,scope}:{runtime:MemberRuntime;scope:ScopeState}){const list=runtime.initiatives.list.bind(runtime.initiatives);const {data,error}=useScoped(scope,list);return <><Page title="Meine Vorschläge" lead="Eigene Initiativen im aktuell autorisierten Organisationsumfang."/><ProgramDraftContext/><ProcessChain/><ScopeSelector scope={scope}/>{error&&<Capability status="BLOCKED" owner="InitiativesPort" reason={error}/>} {data&&<>{data.map(x=><Card key={x.ref} title={x.title}>{x.state} · {x.scopeRef}</Card>)}<Link className="button button--primary" href="/member/initiatives/new">Neue Initiative</Link></>}</>;}
function Deliberation({runtime,scope}:{runtime:MemberRuntime;scope:ScopeState}){const list=runtime.deliberation.list.bind(runtime.deliberation);const {data,error}=useScoped(scope,list);return <><Page title="Programmwerkstatt · Diskussion" lead="Diskussion ist eine Prozessphase und noch keine demokratische Entscheidung."/><ProgramDraftContext/><ProcessChain/><ScopeSelector scope={scope}/>{error&&<Capability status="BLOCKED" owner="DeliberationPort" reason={error}/>} {data?.map(x=><Card key={`${x.title}-${x.version}`} title={x.title}><small>{x.version} · Provenienz: {x.provenance}</small></Card>)}</>;}
function Delegation({runtime,scope}:{runtime:MemberRuntime;scope:ScopeState}){const status=runtime.delegation.status.bind(runtime.delegation);const {data,error}=useScoped(scope,status);return <><Page title="Meine Stimmen & Delegation" lead="Delegationsregeln werden nicht im Frontend erfunden."/><ScopeSelector scope={scope}/><aside className="notice"><strong>Abstimmungen: GEPLANT / NICHT AKTIVIERT</strong><p>eID und sichere Online-Abstimmungen sind Ziel-Fähigkeiten.</p></aside>{error&&<Capability status="BLOCKED" owner="DelegationPort" reason={error}/>} {data&&<Capability status={data.activation} owner="Delegation domain" reason={data.reason}/>}</>;}
function Applicant({runtime}:{runtime:MemberRuntime}){const[data,setData]=useState<ApplicantCase|null>(null);useEffect(()=>{let active=true;void runtime.applicantCase.readOwnCase().then(r=>{if(active&&r.ok)setData(r.value)});return()=>{active=false}},[runtime]);if(!data)return <State title="LOADING" text="Antrag wird geladen" help="Bitte warten."/>;return <><Page title="Mein Aufnahmeantrag" lead="Antragstellerkonto und Mitgliedschaft sind getrennte Zustände."/><aside className="notice"><strong>Applicant ≠ Member</strong><p>Identitätsprüfung oder Kontozugang allein begründen keine Mitgliedschaft.</p></aside><div className="grid"><Card title="Antrag"><strong>{data.reference}</strong></Card><Card title="Status"><strong>{data.status}</strong><p>{data.stage}</p></Card><Card title="Zuständige Stelle">{data.unit}</Card><Card title="Frist">{data.deadline}</Card></div><Link className="button button--secondary" href="/member/membership/appeal">Korrektur / Rechtsbehelf</Link></>;}

function InitiativeFlow({runtime,scopeRef}:{runtime:MemberRuntime;scopeRef:string}){const[step,setStep]=useState<"draft"|"preview"|"confirm"|"submitting"|"receipt"|"error"|"stepup">("draft");const[title,setTitle]=useState("");const[summary,setSummary]=useState("");const[receipt,setReceipt]=useState("");const submitting=useRef(false);const dialog=useRef<HTMLDialogElement>(null);const origin=useRef<HTMLButtonElement>(null);const draft:InitiativeDraft={title,summary,clientRequestRef:"browser-generated-nonidentity-ref",expectedVersion:"1"};async function commit(){if(submitting.current)return;submitting.current=true;setStep("submitting");const principal=await runtime.principal.resolve();if(!principal.ok||principal.value.actor!=="member"||principal.value.assurance==="expired"||principal.value.assurance==="revoked"){submitting.current=false;setStep("error");return}if(principal.value.assurance==="step-up-required"){submitting.current=false;setStep("stepup");return}const r=await runtime.initiatives.commit(scopeRef,draft);submitting.current=false;if(r.ok){setReceipt(r.value.receiptRef);setStep("receipt");dialog.current?.close()}else setStep("error")}
if(step==="receipt")return <><Page title="Initiative verbindlich übermittelt" lead="Erfolg wird erst nach autoritativer Commit-Bestätigung gezeigt."/><Card title="Quittung"><strong>{receipt}</strong><p>Status: committed</p></Card></>;if(step==="error")return <State title="BLOCKED" text="Übermittlung nicht bestätigt" help="Ohne autoritative Bestätigung wird kein Erfolg angezeigt."/>;if(step==="stepup")return <State title="BLOCKED" text="Zusätzliche Bestätigung erforderlich" help="Die Aktion wurde nicht ausgeführt."/>;return <><Page title="Problem / Vorschlag einreichen" lead="Entwurf → Vorschau → ausdrückliche Bestätigung → autoritativer Commit → Quittung."/><ProgramDraftContext/><ProcessChain/>{step==="draft"?<form onSubmit={e=>{e.preventDefault();setStep("preview")}}><label>Titel<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Kurzbeschreibung<textarea required value={summary} onChange={e=>setSummary(e.target.value)}/></label><button className="button button--primary">Vorschau</button></form>:<Card title="Vorschau"><h2>{title}</h2><p>{summary}</p><button ref={origin} className="button button--primary" onClick={()=>{setStep("confirm");dialog.current?.showModal()}}>Verbindlich übermitteln…</button></Card>}<dialog ref={dialog} onClose={()=>origin.current?.focus()} aria-labelledby="confirm-title"><h2 id="confirm-title">Übermittlung bestätigen</h2><p>Erfolg erst nach autoritativer Bestätigung.</p><button className="button button--secondary" onClick={()=>{dialog.current?.close();setStep("preview")}}>Abbrechen</button><button className="button button--primary" disabled={step==="submitting"} onClick={()=>void commit()}>{step==="submitting"?"Wird übermittelt…":"Jetzt bestätigen"}</button></dialog></>;}
