import type { WorkspacePolicy } from "./types";

const base = { sessionSharing: "forbidden" } as const;

export const WORKSPACES: readonly WorkspacePolicy[] = [
  {
    ...base,
    id: "WS-01",
    name: "Public Website",
    originPlaceholder: "https://www.epd.example",
    routePrefix: "/",
    shell: "public",
    navigationSource: "public-navigation",
    capabilities: ["approved-renditions", "explicit-handoff"],
    sensitivity: "PUBLIC_APPROVED",
    analytics: "aggregate-first-party",
    browserStorage: "preferences-only",
    activation: "design-baseline",
  },
  {
    ...base,
    id: "WS-02",
    name: "Member Application",
    originPlaceholder: "https://app.epd.example",
    routePrefix: "/Member",
    shell: "member",
    navigationSource: "member-navigation",
    capabilities: ["member-shell", "step-up-notice"],
    sensitivity: "INTERNAL; CONFIDENTIAL_CASE_SCOPED",
    analytics: "workspace-operational",
    browserStorage: "preferences-only",
    activation: "wave-1-gated",
  },
  {
    ...base,
    id: "WS-03",
    name: "Voting Client",
    originPlaceholder: "https://vote.epd.example",
    routePrefix: "/vote",
    shell: "voting",
    navigationSource: "voting-navigation",
    capabilities: ["isolation-ready-shell", "one-time-purpose-scoped-handoff"],
    sensitivity: "VOTING_SCOPED; NO_DIRECT_IDENTITY",
    analytics: "none",
    browserStorage: "none",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-04",
    name: "Mandate Holder Workspace",
    originPlaceholder: "https://represent.epd.example",
    routePrefix: "/Mandate Holder",
    shell: "institutional",
    navigationSource: "mandate-navigation",
    capabilities: ["authority-notice", "scope-notice"],
    sensitivity: "MANDATE_INTERNAL; CASE_CONFIDENTIAL",
    analytics: "workspace-operational",
    browserStorage: "preferences-only",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-05",
    name: "Citizen Office Portal",
    originPlaceholder: "https://office.epd.example",
    routePrefix: "/office",
    shell: "institutional",
    navigationSource: "office-navigation",
    capabilities: ["case-status-shell", "consent-notice"],
    sensitivity: "CASE_CONFIDENTIAL; SPECIAL_CATEGORY_POSSIBLE",
    analytics: "none",
    browserStorage: "purpose-specific",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-06",
    name: "Institutional Administration",
    originPlaceholder: "https://admin.epd.example",
    routePrefix: "/admin",
    shell: "institutional",
    navigationSource: "role-specific-admin-navigation",
    capabilities: ["dual-control-notice", "restricted-content-notice"],
    sensitivity: "RESTRICTED_ADMIN; SECURITY_SENSITIVE",
    analytics: "security-only",
    browserStorage: "none",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-07",
    name: "Compliance & Legal Workspace",
    originPlaceholder: "https://legal.epd.example",
    routePrefix: "/legal",
    shell: "institutional",
    navigationSource: "legal-navigation",
    capabilities: ["legal-effect-warning", "provenance"],
    sensitivity: "LEGAL_PRIVILEGED; EVIDENCE_RESTRICTED",
    analytics: "none",
    browserStorage: "none",
    activation: "candidate-gated",
  },
  {
    ...base,
    id: "WS-08",
    name: "Finance Workspace",
    originPlaceholder: "https://finance.epd.example",
    routePrefix: "/finance",
    shell: "institutional",
    navigationSource: "finance-navigation",
    capabilities: ["dual-control-notice", "audit-summary"],
    sensitivity: "FINANCIAL_CONFIDENTIAL",
    analytics: "workspace-operational",
    browserStorage: "none",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-09",
    name: "Independent Oversight & Verification",
    originPlaceholder: "https://verify.epd.example",
    routePrefix: "/verify",
    shell: "institutional",
    navigationSource: "oversight-navigation",
    capabilities: ["independence-notice", "evidence-summary"],
    sensitivity: "OVERSIGHT_RESTRICTED; PUBLIC_VERIFICATION",
    analytics: "none",
    browserStorage: "none",
    activation: "planned",
  },
  {
    ...base,
    id: "WS-10",
    name: "Transparency Publication Portal",
    originPlaceholder: "https://transparency.epd.example",
    routePrefix: "/transparency",
    shell: "publication",
    navigationSource: "publication-navigation",
    capabilities: ["publication-state", "correction-link", "provenance"],
    sensitivity: "PUBLIC_APPROVED; AGGREGATED_DISCLOSURE_CONTROLLED",
    analytics: "aggregate-first-party",
    browserStorage: "preferences-only",
    activation: "planned",
  },
] as const;

export function workspaceById(id: WorkspacePolicy["id"]): WorkspacePolicy {
  const workspace = WORKSPACES.find((candidate) => candidate.id === id);
  if (!workspace) throw new Error(`Unknown workspace: ${id}`);
  return workspace;
}
