"""Canonical test-vector suite (PACK-16D §38).

**Provenance, stated first because it governs how these may be used.**
Every vector in this catalogue is *self-generated* by this reference
implementation on the ``EPD2-TESTONLY-NOTCONFORMANT-P1024-Q160`` and
``EPD2-TESTONLY-NOTCONFORMANT-P4096-Q256`` test profiles. None is an external conformance
vector, because the published ElectionGuard 2.1 constants could not be
obtained first-hand in this round (`OD-P16D-01`). A self-generated vector
proves *determinism and stability* — that a change to encoding, domain
separation or hashing is detected — and proves nothing whatsoever about
agreement with any other implementation. Interoperability evidence is a
PACK-17 obligation and is recorded as such.

Each vector carries: id, profile version, input canonical bytes, expected
output, explanation, source, status.

Vectors are deterministic by construction: every random value comes from
``DeterministicTestRandomSource`` under a fixed seed, so regenerating the
catalogue on an unchanged implementation is byte-identical. That property
is the actual test.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass

from epd2_voting_service.reference.casting.ballot import encrypt_ballot
from epd2_voting_service.reference.casting.confirmation import derive_confirmation_code
from epd2_voting_service.reference.crypto.domain_separation import DomainLabel
from epd2_voting_service.reference.crypto.elgamal import accumulate, encrypt
from epd2_voting_service.reference.crypto.encoding import (
    encode_bytes,
    encode_group_element,
    encode_scalar,
    encode_struct,
    encode_text,
    encode_uint,
)
from epd2_voting_service.reference.crypto.hashing import ZERO_KEY, h
from epd2_voting_service.reference.crypto.merkle import (
    consistency_proof,
    inclusion_proof,
)
from epd2_voting_service.reference.crypto.merkle import root as merkle_tree_root
from epd2_voting_service.reference.crypto.parameters import ParameterSet
from epd2_voting_service.reference.crypto.proofs import (
    prove_decryption_share,
    prove_selection,
)
from epd2_voting_service.reference.election_record.builder import (
    ReconciliationRecord,
)
from epd2_voting_service.reference.publication.sealed_batches import (
    LeafClass,
    LeafOpening,
    cover_leaf,
    real_leaf,
)
from epd2_voting_service.reference.testing.fixtures import (
    deterministic_source,
    small_params,
)
from epd2_voting_service.reference.verification.results import (
    EXIT_CODES,
    VerificationResult,
    VerificationResultCode,
)

CATALOG_VERSION = "EPD2-VECTORS-1"

#: The single honest provenance string. Do not soften it.
SELF_GENERATED = (
    "self-generated by the PACK-16D reference implementation on a TEST profile; "
    "NOT an external conformance vector"
)

#: Status vocabulary. ``stability`` means the vector pins this
#: implementation's own output; ``interoperability`` would mean agreement
#: with an external implementation and is not claimed by any vector here.
STATUS_STABILITY = "stability-only (interoperability NOT established)"


@dataclass(frozen=True, slots=True)
class TestVector:
    vector_id: str
    family: str
    profile_version: str
    input_canonical_bytes: str
    expected_output: str
    explanation: str
    source: str
    status: str


def _v(
    vector_id: str,
    family: str,
    params: ParameterSet | None,
    input_bytes: bytes,
    output: bytes,
    explanation: str,
) -> TestVector:
    return TestVector(
        vector_id=vector_id,
        family=family,
        profile_version=params.parameter_set_id if params else "n/a",
        input_canonical_bytes=input_bytes.hex(),
        expected_output=output.hex(),
        explanation=explanation,
        source=SELF_GENERATED,
        status=STATUS_STABILITY,
    )


def build_catalog() -> list[TestVector]:
    """Twenty-one vector families, in the order §38 lists them."""
    params = small_params()
    source = deterministic_source(b"epd2-pack-16d-vectors")
    vectors: list[TestVector] = []

    # 1. parameter validation
    vectors.append(
        _v(
            "TV-01-parameter-validation",
            "parameter validation",
            params,
            params.canonical_bytes(),
            params.digest(),
            "Digest over the canonical parameter-set encoding. A change to p, "
            "q, g or the encoding changes this value.",
        )
    )

    # 2. group element encoding
    vectors.append(
        _v(
            "TV-02-group-element-encoding",
            "group element encoding",
            params,
            params.g.to_bytes((params.g.bit_length() + 7) // 8, "big"),
            encode_group_element(params.g, params.p_bytes),
            "Input is the minimal big-endian form of g; output is the canonical "
            "fixed-width form at |p| bytes. No short form is ever accepted.",
        )
    )

    # 3. scalar encoding
    vectors.append(
        _v(
            "TV-03-scalar-encoding",
            "scalar encoding",
            params,
            encode_uint(7, 8),
            encode_scalar(7, params.q_bytes),
            "A scalar is fixed-width at |q| bytes; 7 encodes with leading zeros.",
        )
    )

    # 4. domain-separated hashes
    label_probe = encode_text("probe")
    vectors.append(
        _v(
            "TV-04-domain-separated-hash",
            "domain-separated hashes",
            None,
            label_probe,
            h(ZERO_KEY, DomainLabel.BALLOT_HASH, [label_probe]),
            "The same input under a different label must produce a different "
            "digest; this vector pins one label.",
        )
    )

    # 5. selection encryption
    secret = 1 + source.random_below(params.q - 1)
    public_key = pow(params.g, secret, params.p)
    nonce = 1 + source.random_below(params.q - 1)
    ciphertext = encrypt(1, nonce, public_key, params)
    vectors.append(
        _v(
            "TV-05-selection-encryption",
            "selection encryption",
            params,
            encode_struct(
                [
                    ("message", encode_uint(1, 4)),
                    ("nonce", encode_scalar(nonce, params.q_bytes)),
                    ("public_key", encode_group_element(public_key, params.p_bytes)),
                ]
            ),
            ciphertext.canonical_bytes(params),
            "Exponential ElGamal encryption of m=1 under a fixed nonce.",
        )
    )

    # 6. selection proof
    selection_proof = prove_selection(
        ciphertext, nonce, 1, public_key, params, b"vector-context", source
    )
    vectors.append(
        _v(
            "TV-06-selection-proof",
            "selection proof",
            params,
            ciphertext.canonical_bytes(params),
            selection_proof.canonical_bytes(params),
            "Disjunctive Chaum-Pedersen proof that the plaintext is 0 or 1.",
        )
    )

    # 7. contest proof + 8. ballot hash + 10. challenge opening
    from epd2_voting_service.reference.testing.fixtures import fixture_a

    fixture = fixture_a(params)
    envelope, opening = encrypt_ballot(
        fixture.manifest,
        "style-a",
        {"c1": ("opt-1",)},
        fixture.public_key,
        params,
        fixture.base_hash,
        deterministic_source(b"epd2-pack-16d-vector-ballot"),
    )
    vectors.append(
        _v(
            "TV-07-contest-proof",
            "contest proof",
            params,
            envelope.contests[0].accumulated.canonical_bytes(params),
            envelope.contests[0].sum_proof.canonical_bytes(params),
            "Chaum-Pedersen proof that the contest accumulates to exactly the "
            "selection limit, placeholders included.",
        )
    )
    vectors.append(
        _v(
            "TV-08-ballot-hash",
            "ballot hash",
            params,
            envelope.canonical_bytes(params),
            envelope.digest(params),
            "Digest over the canonical ballot envelope. Carries no identity.",
        )
    )
    vectors.append(
        _v(
            "TV-09-confirmation-code",
            "confirmation code",
            params,
            envelope.canonical_bytes(params),
            derive_confirmation_code(envelope, params, fixture.base_hash).encode(),
            "Confirmation code derived from the encryptions and H_E only; it "
            "is not a proof of how the voter voted.",
        )
    )
    vectors.append(
        _v(
            "TV-10-challenge-opening",
            "challenge opening",
            params,
            encode_struct(
                [
                    ("ballot_id", encode_text(opening.ballot_id)),
                    (
                        "nonces",
                        encode_struct(
                            [(o, encode_scalar(n, params.q_bytes)) for o, n in opening.nonces]
                        ),
                    ),
                ]
            ),
            envelope.digest(params),
            "The published opening re-encrypts to exactly the published "
            "envelope digest. Publishing it reveals the choice, by design.",
        )
    )

    # 11. ciphertext accumulation
    aggregate = accumulate([s.ciphertext for s in envelope.contests[0].selections], params)
    vectors.append(
        _v(
            "TV-11-ciphertext-accumulation",
            "ciphertext accumulation",
            params,
            encode_struct(
                [
                    (f"c{i}", s.ciphertext.canonical_bytes(params))
                    for i, s in enumerate(envelope.contests[0].selections)
                ]
            ),
            aggregate.canonical_bytes(params),
            "Componentwise multiplication is the homomorphic sum.",
        )
    )

    # 12. decryption share
    share_value = pow(aggregate.alpha, fixture.secret, params.p)
    share_proof = prove_decryption_share(
        aggregate.alpha,
        share_value,
        fixture.secret,
        fixture.public_key,
        params,
        b"tally",
        deterministic_source(b"epd2-pack-16d-vector-share"),
    )
    vectors.append(
        _v(
            "TV-12-decryption-share",
            "decryption share",
            params,
            encode_group_element(aggregate.alpha, params.p_bytes),
            encode_struct(
                [
                    ("share", encode_group_element(share_value, params.p_bytes)),
                    ("proof", share_proof.canonical_bytes(params)),
                ]
            ),
            "Partial decryption with its Chaum-Pedersen proof of correct exponentiation.",
        )
    )

    # 13. tally result
    reconciliation = ReconciliationRecord(
        accepted_cast=1, public_challenged_spoiled=1, cover=14, max_valid_continuations=4, k=1, a=1
    )
    vectors.append(
        _v(
            "TV-13-tally-result",
            "tally result",
            params,
            reconciliation.canonical_bytes(),
            h(ZERO_KEY, DomainLabel.TALLY, [reconciliation.canonical_bytes()]),
            "Digest over a reconciliation record: one accepted cast, one "
            "public challenge, fourteen cover leaves, E=4, K=1, A=1.",
        )
    )

    # 14. batch leaf
    leaf_opening = LeafOpening(
        leaf_index=0,
        leaf_class=LeafClass.ACCEPTED_CAST,
        salt=bytes(range(32)),
        artifact_reference="ballot-ref",
        artifact_digest=bytes(32),
    )
    vectors.append(
        _v(
            "TV-14-batch-leaf",
            "batch leaf",
            None,
            leaf_opening.canonical_bytes(),
            real_leaf("fixture-a", 0, leaf_opening),
            "A real leaf is a hiding commitment under a 32-byte salt.",
        )
    )

    # 15. cover leaf
    cover_source = deterministic_source(b"epd2-pack-16d-vector-cover")
    cover = cover_leaf(cover_source)
    vectors.append(
        _v(
            "TV-15-cover-leaf",
            "cover leaf",
            None,
            b"",
            cover,
            "A cover leaf is uniform random of the leaf's exact size. It is "
            "not a hash of anything and has no opening.",
        )
    )

    # 16. batch root
    leaves = [real_leaf("fixture-a", 0, leaf_opening), cover]
    vectors.append(
        _v(
            "TV-16-batch-root",
            "batch root",
            None,
            encode_struct([("l0", encode_bytes(leaves[0])), ("l1", encode_bytes(leaves[1]))]),
            merkle_tree_root(leaves),
            "RFC 6962 shaped Merkle root over one real and one cover leaf.",
        )
    )

    # 17. inclusion proof
    eight = [f"leaf-{i}".encode() for i in range(8)]
    path = inclusion_proof(eight, 3)
    vectors.append(
        _v(
            "TV-17-inclusion-proof",
            "inclusion proof",
            None,
            encode_struct([("leaf_index", encode_uint(3, 4))]),
            encode_struct(
                [(f"{i}:{side}", encode_bytes(node)) for i, (side, node) in enumerate(path)]
            ),
            "Sibling path for leaf 3 of an 8-leaf tree, as (side, digest) pairs.",
        )
    )

    # 18. consistency proof
    proof = consistency_proof(eight, 5)
    vectors.append(
        _v(
            "TV-18-consistency-proof",
            "consistency proof",
            None,
            encode_struct([("old_size", encode_uint(5, 8)), ("new_size", encode_uint(8, 8))]),
            encode_struct([(str(i), encode_bytes(n)) for i, n in enumerate(proof)]),
            "RFC 6962 consistency proof from tree size 5 to tree size 8. "
            "Old size 5 is not a power of two, so its root is not implicit.",
        )
    )

    # 19. election-record digest
    vectors.append(
        _v(
            "TV-19-election-record-digest",
            "election-record digest",
            params,
            fixture.manifest.canonical_bytes(),
            h(ZERO_KEY, DomainLabel.ELECTION_RECORD, [fixture.manifest.canonical_bytes()]),
            "Digest over the manifest under the election-record label. A "
            "record digest is domain-separated from every other digest.",
        )
    )

    # 20. verification result
    result = VerificationResult(
        VerificationResultCode.VERIFIED, checks_run=("parameter_set", "tally_recomputation")
    )
    vectors.append(
        _v(
            "TV-20-verification-result",
            "verification result",
            None,
            encode_text(result.code.value),
            encode_struct(
                [
                    ("code", encode_text(result.code.value)),
                    ("exit_code", encode_uint(result.exit_code, 4)),
                    (
                        "checks_run",
                        encode_struct([(c, encode_uint(1, 1)) for c in result.checks_run]),
                    ),
                ]
            ),
            "VERIFIED maps to exit code 0. Exit codes are stable and never renumbered.",
        )
    )

    # 21. exit-code table
    vectors.append(
        _v(
            "TV-21-exit-code-table",
            "verification result",
            None,
            b"",
            encode_struct(
                [(code.value, encode_uint(value, 4)) for code, value in EXIT_CODES.items()]
            ),
            "The complete exit-code table, pinned so a renumbering is a test "
            "failure rather than a silent contract change.",
        )
    )

    # 22. the production-shaped profile, so the catalogue is not entirely
    # built on the small fast profile. Only the cheap operations are run
    # here: a 4096-bit encrypt-and-prove cycle costs over a second, which
    # is not worth paying on every test run to pin a value the 1024-bit
    # vectors already pin structurally.
    from epd2_voting_service.reference.testing.fixtures import production_shaped_params

    large = production_shaped_params()
    vectors.append(
        _v(
            "TV-22-production-shaped-parameter-set",
            "parameter validation",
            large,
            large.canonical_bytes(),
            large.digest(),
            "The 4096/256 TEST profile's parameter digest. Same SHAPE as "
            "EPD2-CRYPTO-1 and carrying the same q, but NOT the published "
            "ElectionGuard 2.1 constants and never a production default.",
        )
    )
    vectors.append(
        _v(
            "TV-23-production-shaped-group-encoding",
            "group element encoding",
            large,
            large.g.to_bytes((large.g.bit_length() + 7) // 8, "big"),
            encode_group_element(large.g, large.p_bytes),
            "A group element on the 4096-bit profile encodes to exactly 512 "
            "bytes; the width follows |p| and never the value.",
        )
    )

    return vectors


def serialize(vectors: list[TestVector]) -> str:
    """Stable JSON. Field order follows the dataclass, never sorted."""
    payload = {
        "catalog_version": CATALOG_VERSION,
        "provenance": SELF_GENERATED,
        "vector_count": len(vectors),
        "vectors": [asdict(v) for v in vectors],
    }
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"
