"""INFRA-03 detector codes.

One namespace (``I03_``) of distinct, fail-closed detector codes. Every
mutation class of the governed suite maps onto exactly one of these codes —
no shared poison marker — and every code names the defect it refuses.
"""

# -- artifact identity / supply-chain handoff (assignment §9, §49) ---------
MUTABLE_ARTIFACT_REFERENCE = "I03_MUTABLE_ARTIFACT_REFERENCE"
ARTIFACT_DIGEST_MISMATCH = "I03_ARTIFACT_DIGEST_MISMATCH"
LOCAL_REBUILD_SUBSTITUTION = "I03_LOCAL_REBUILD_SUBSTITUTION"
SUPPLY_CHAIN_HANDOFF_BYPASSED = "I03_SUPPLY_CHAIN_HANDOFF_BYPASSED"
STALE_PREDECESSOR = "I03_STALE_PREDECESSOR"

# -- topology / catalog / segmentation (§7, §8, §18) -----------------------
TOPOLOGY_INCOMPLETE = "I03_TOPOLOGY_INCOMPLETE"
UNDECLARED_SERVICE = "I03_UNDECLARED_SERVICE"
ADMIN_ENDPOINT_PUBLIC = "I03_ADMIN_ENDPOINT_PUBLIC"
WRONG_NETWORK_SEGMENT = "I03_WRONG_NETWORK_SEGMENT"
UNDECLARED_FLOW = "I03_UNDECLARED_FLOW"
UNDECLARED_EGRESS = "I03_UNDECLARED_EGRESS"
ENVIRONMENT_CATALOG_INVALID = "I03_ENVIRONMENT_CATALOG_INVALID"

# -- ingress / TLS / mTLS / trust (§21, §23, §24, §16) ---------------------
FORWARDED_HEADER_UNTRUSTED = "I03_FORWARDED_HEADER_UNTRUSTED"
PLAINTEXT_FALLBACK_FORBIDDEN = "I03_PLAINTEXT_FALLBACK_FORBIDDEN"
UNTRUSTED_CA = "I03_UNTRUSTED_CA"
HOSTNAME_MISMATCH = "I03_HOSTNAME_MISMATCH"
CLIENT_CERT_MISSING = "I03_CLIENT_CERT_MISSING"
WORKLOAD_IDENTITY_MISMATCH = "I03_WORKLOAD_IDENTITY_MISMATCH"
UNIVERSAL_SERVICE_CERT = "I03_UNIVERSAL_SERVICE_CERT"
TRUST_MATERIAL_INVALID = "I03_TRUST_MATERIAL_INVALID"

# -- secrets / config (§14, §25, §26) --------------------------------------
SECRET_IN_MANIFEST = "I03_SECRET_IN_MANIFEST"
SECRET_IN_LOGS = "I03_SECRET_IN_LOGS"
SECRET_INJECTION_UNCLASSIFIED = "I03_SECRET_INJECTION_UNCLASSIFIED"
CONFIG_INVALID_STARTUP = "I03_CONFIG_INVALID_STARTUP"
PERMISSIVE_DEFAULT_FORBIDDEN = "I03_PERMISSIVE_DEFAULT_FORBIDDEN"

# -- PostgreSQL / persistence (§12, §13, §34, §36) -------------------------
PRODUCTION_DB_IN_PREVIEW = "I03_PRODUCTION_DB_IN_PREVIEW"
NON_POSTGRES_SUBSTITUTION = "I03_NON_POSTGRES_SUBSTITUTION"
MIGRATION_LEDGER_VIOLATION = "I03_MIGRATION_LEDGER_VIOLATION"
STALE_STATE_AFTER_RESET = "I03_STALE_STATE_AFTER_RESET"
PERSISTENCE_CLASS_VIOLATION = "I03_PERSISTENCE_CLASS_VIOLATION"

# -- health / readiness / lifecycle (§28..§31, §43) ------------------------
READINESS_ALWAYS_TRUE = "I03_READINESS_ALWAYS_TRUE"
SENSITIVE_HEALTH_OUTPUT = "I03_SENSITIVE_HEALTH_OUTPUT"
SLEEP_BASED_READINESS = "I03_SLEEP_BASED_READINESS"
CRASHLOOP_MARKED_HEALTHY = "I03_CRASHLOOP_MARKED_HEALTHY"
FAILED_DEPLOY_MARKED_SUCCESS = "I03_FAILED_DEPLOY_MARKED_SUCCESS"
PARTIAL_UNSAFE_EXPOSURE = "I03_PARTIAL_UNSAFE_EXPOSURE"

# -- deploy lifecycle (§32, §41, §42, §40, §47) ----------------------------
UNSAFE_ROLLBACK = "I03_UNSAFE_ROLLBACK"
NON_IDEMPOTENT_REDEPLOY = "I03_NON_IDEMPOTENT_REDEPLOY"
DRIFT_IGNORED = "I03_DRIFT_IGNORED"
AMBIGUOUS_DESTRUCTIVE_TARGET = "I03_AMBIGUOUS_DESTRUCTIVE_TARGET"
ENVIRONMENT_ISOLATION_BREACH = "I03_ENVIRONMENT_ISOLATION_BREACH"
CLEAN_ROOM_VIOLATION = "I03_CLEAN_ROOM_VIOLATION"
RESOURCE_BOUNDARY_UNDECLARED = "I03_RESOURCE_BOUNDARY_UNDECLARED"

# -- voting isolation / observability privacy (§20, §38, §39) --------------
VOTING_PERSON_ID_LEAK = "I03_VOTING_PERSON_ID_LEAK"
VOTING_GLOBAL_CORRELATION = "I03_VOTING_GLOBAL_CORRELATION"
SHARED_VOTING_OBSERVABILITY = "I03_SHARED_VOTING_OBSERVABILITY"
OBSERVABILITY_PRIVACY_VIOLATION = "I03_OBSERVABILITY_PRIVACY_VIOLATION"

# -- failure semantics (§44, §45) ------------------------------------------
HIDDEN_FAILURE_SUCCESS = "I03_HIDDEN_FAILURE_SUCCESS"
DUPLICATE_CONSEQUENTIAL_OPERATION = "I03_DUPLICATE_CONSEQUENTIAL_OPERATION"

# -- packaging / evidence (§61, §62) ---------------------------------------
POST_TEST_BYTE_MUTATION = "I03_POST_TEST_BYTE_MUTATION"
STALE_EVIDENCE_REUSED = "I03_STALE_EVIDENCE_REUSED"
GATE_NOT_EXECUTED = "I03_GATE_NOT_EXECUTED"
