from pathlib import Path
import sys
root=Path(sys.argv[1])
p=root/'scripts/infra03/trust.py'; s=p.read_text()
needle='.add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)\n'
repl=needle+'            .add_extension(x509.SubjectKeyIdentifier.from_public_key(self._key.public_key()), critical=False)\n            .add_extension(x509.AuthorityKeyIdentifier.from_issuer_public_key(self._key.public_key()), critical=False)\n'
if 'SubjectKeyIdentifier.from_public_key(self._key.public_key())' not in s: s=s.replace(needle,repl)
needle='.add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)\n'
repl=needle+'            .add_extension(x509.SubjectKeyIdentifier.from_public_key(key.public_key()), critical=False)\n            .add_extension(x509.AuthorityKeyIdentifier.from_issuer_public_key(self._key.public_key()), critical=False)\n'
if 'SubjectKeyIdentifier.from_public_key(key.public_key())' not in s: s=s.replace(needle,repl)
p.write_text(s)
p=root/'scripts/infra03/gates.py'; s=p.read_text()
s=s.replace('G41 (API-06 reconciliation) is truthfully ``BLOCKED_FOR_FINAL_SEAL /\nDEVELOPMENT_MAY_CONTINUE`` while API-06 has no authoritative acceptance —\nnever a fake PASS.', 'G41 (API-06 reconciliation) verifies the live canonical API-06 acceptance record,\nPCR closure and exact accepted API-06 candidate bytes; any mismatch fails closed.')
s=s.replace('fails closed. Anti-cheat', 'fails closed.\nAnti-cheat')
s=s.replace('def __init__(self, root: Path, artifact_zip: Path, instance_base: Path | None = None) -> None:', 'def __init__(self, root: Path, artifact_zip: Path, instance_base: Path | None = None, api06_artifact: Path | None = None) -> None:')
s=s.replace('        self.instance_base = instance_base or Path("/tmp/epd2-infra03-gates")\n', '        self.instance_base = instance_base or Path("/tmp/epd2-infra03-gates")\n        self.api06_artifact = api06_artifact\n')
old='''        self._record(\n            "G41",\n            "BLOCKED_FOR_FINAL_SEAL / DEVELOPMENT_MAY_CONTINUE",\n            "API-06 has no authoritative acceptance (API-06 = NEXT on the live "\n            "register); exact accepted API-06 reconciliation is impossible and is "\n            "not faked. Final seal is blocked until it exists.",\n            "baseline_identity.json",\n        )'''
if old in s: s=s.replace(old,'        self._gate_api06_reconciliation()')
marker='    def _runtime_gates(self, supervisor: Supervisor, topology: dict[str, Any]) -> None:\n'
if 'def _gate_api06_reconciliation' not in s:
    method='''    def _gate_api06_reconciliation(self) -> None:\n        record_path = "docs/api/API-06/API06_C1_ACCEPTANCE_RECORD.json"\n        findings: list[str] = []\n        try:\n            record_bytes = subprocess.run(["git", "-C", str(self.root), "show", f"origin/main:{record_path}"], capture_output=True, timeout=120, check=True).stdout\n            record = json.loads(record_bytes)\n        except (subprocess.CalledProcessError, json.JSONDecodeError) as error:\n            record = {}\n            findings.append(f"authoritative API-06 acceptance record unavailable: {error}")\n        pcr = subprocess.run(["git", "-C", str(self.root), "show", "origin/main:docs/roadmap/EPD2_PROGRAM_CONTROL_REGISTER.md"], capture_output=True, text=True, timeout=120, check=True).stdout\n        expected = str(record.get("candidate", {}).get("sha256", ""))\n        decision = str(record.get("decision", ""))\n        actual = sha256_file(self.api06_artifact) if self.api06_artifact and self.api06_artifact.is_file() else "ABSENT"\n        if "API-06 = ACCEPTED / CLOSED" not in pcr or "API = CLOSED" not in pcr: findings.append("canonical PCR does not close API-06/API layer")\n        if "ACCEPTED" not in decision.upper(): findings.append(f"API-06 acceptance decision is {decision!r}")\n        if not expected: findings.append("API-06 acceptance record has no candidate SHA-256")\n        if actual != expected: findings.append(f"exact API-06 candidate mismatch: expected {expected or 'MISSING'}, got {actual}")\n        evidence = self._emit("api06_reconciliation_result.json", {"acceptance_record": record_path, "decision": decision, "expected_candidate": {"sha256": expected}, "staged_candidate": {"path": str(self.api06_artifact) if self.api06_artifact else None, "sha256": actual}, "findings": findings})\n        self._from_findings("G41", findings, f"exact accepted API-06 candidate {expected[:12]} reconciled", evidence)\n\n'''
    s=s.replace(marker,method+marker)
s=s.replace('        verdict = "PASS_WITH_GOVERNED_BLOCKERS" if runnable_fail == 0 else "FAIL"\n','        blockers = counts.get("BLOCKED", 0)\n        verdict = "PASS" if runnable_fail == 0 and blockers == 0 else ("PASS_WITH_GOVERNED_BLOCKERS" if runnable_fail == 0 else "FAIL")\n')
old='''                "final_seal_blockers": [\n                    "canonical governance has not promoted/opened INFRA-03 (proposed "\n                    "working contract only)",\n                    "API-06 has no authoritative acceptance (G41 BLOCKED_FOR_FINAL_SEAL)",\n                ],'''
if old in s: s=s.replace(old,'''                "final_seal_blockers": [] if verdict == "PASS" else ["one or more governed runtime gates remain FAIL/BLOCKED"],''')
s=s.replace('EPD2_INFRA03_DEPLOYMENT_RUNTIME_AND_PREVIEW_READINESS_WORKING_0.1_PRESEAL','EPD2_INFRA03_DEPLOYMENT_RUNTIME_AND_PREVIEW_READINESS_CANDIDATE_0.1_C1')
s=s.replace('    parser.add_argument("--instance-base", default=None)\n','    parser.add_argument("--instance-base", default=None)\n    parser.add_argument("--api06-artifact", default=None, help="exact accepted API-06 candidate ZIP")\n')
s=s.replace('''        Path(args.instance_base).resolve() if args.instance_base else None,\n    )\n    verdict = runner.run_runtime_phase()\n    return 0 if verdict == "PASS_WITH_GOVERNED_BLOCKERS" else 1''','''        Path(args.instance_base).resolve() if args.instance_base else None,\n        Path(args.api06_artifact).resolve() if args.api06_artifact else None,\n    )\n    verdict = runner.run_runtime_phase()\n    return 0 if verdict == "PASS" else 1''')
p.write_text(s)
for rel in ['scripts/infra03/preseal.py','scripts/acceptance/__main__.py','docs/infra/INFRA-03/INFRA03_DEVELOPER_REPORT.md']:
    p=root/rel; s=p.read_text().replace('EPD2_INFRA03_DEPLOYMENT_RUNTIME_AND_PREVIEW_READINESS_WORKING_0.1_PRESEAL','EPD2_INFRA03_DEPLOYMENT_RUNTIME_AND_PREVIEW_READINESS_CANDIDATE_0.1_C1'); p.write_text(s)
print('INFRA03_C1_PATCH_APPLIED')
