import type { PublicPage } from "./content";

export const front02PublicPages: readonly PublicPage[] = [
  {
    id: "FRONT02-PAGE-001",
    path: "/aktuelles",
    title: "Aktuelles",
    eyebrow: "Freigegebene öffentliche Mitteilungen",
    lead: "Veröffentlichungen erscheinen hier erst nach der zuständigen Freigabe. Ein redaktioneller Platzhalter wird nicht als Nachricht ausgegeben.",
    status: "planned",
    pack: "PACK-28 / WS-10",
    prerequisites: "Freigegebene Publikationsprojektion",
    kind: "standard",
    sections: [
      { title: "Noch keine freigegebenen Mitteilungen", text: "Sobald eine geprüfte öffentliche Rendition verfügbar ist, zeigt diese Seite Datum, Kategorie, herausgebende Rolle, Version und Korrekturweg." },
      { title: "Veröffentlichung bleibt nachvollziehbar", text: "Eine spätere Detailseite verknüpft die freigegebene Fassung mit ihrem Herkunfts- und Korrekturhinweis." },
    ],
  },
  {
    id: "FRONT02-PAGE-002",
    path: "/presse",
    title: "Presse",
    eyebrow: "Pressezentrum · freigegebene Renditionen",
    lead: "Pressemitteilungen, Stellungnahmen und freigegebene Materialien werden versioniert veröffentlicht.",
    status: "planned",
    pack: "PACK-28 / WS-10",
    prerequisites: "Freigegebene Publikationsprojektion und Pressestelle",
    kind: "standard",
    sections: [
      { title: "Noch keine Pressemitteilungen freigegeben", text: "Es werden keine beispielhaften oder fiktiven Meldungen als echte Presseinformation dargestellt." },
      { title: "Was eine Veröffentlichung ausweist", text: "Datum, herausgebende Rolle, Version, Korrektur- oder Ersetzungsstatus und ein Kontaktweg gehören zu jeder späteren Rendition." },
    ],
  },
  {
    id: "FRONT02-PAGE-003",
    path: "/termine",
    title: "Termine",
    eyebrow: "Öffentliche Veranstaltungen",
    lead: "Hier erscheinen nur freigegebene öffentliche Termine. Teilnahme-, Versammlungs- oder Abstimmungsfunktionen gehören nicht zu dieser Seite.",
    status: "planned",
    pack: "PACK-21 / PACK-28",
    prerequisites: "Freigegebene öffentliche Veranstaltungsprojektion",
    kind: "standard",
    sections: [{ title: "Noch keine Termine veröffentlicht", text: "Wenn ein Termin freigegeben wird, zeigt seine Detailseite Zeitpunkt, Ort oder Zugangshinweis, Barrierefreiheit und einen Kontaktweg." }],
  },
  {
    id: "FRONT02-PAGE-004",
    path: "/regionen",
    title: "Regionen",
    eyebrow: "Ein EPD²-Auftritt · organisationell eingegrenzt",
    lead: "Regionale Informationen werden als freigegebene Projektionen innerhalb derselben EPD²-Plattform dargestellt – nicht als unabhängige lokale Websites.",
    status: "specified",
    pack: "PACK-08 / PACK-28",
    prerequisites: "Autoritative Organisationsdaten und freigegebene öffentliche Projektionen",
    kind: "standard",
    sections: [
      { title: "Meine Region finden", text: "Die spätere Suche führt nur zu freigegebenen öffentlichen Organisationen. Sie erstellt keine Mitgliedschaft, Zuständigkeit oder Berechtigung." },
      { title: "Was ein regionaler Hub zeigt", text: "Übersicht, Aktuelles, Termine, Initiativen, Personen, Wahlen, Dokumente & Transparenz und Kontakt werden jeweils aus ihren zentralen, organisationsbezogenen Quellen projiziert." },
    ],
  },
  {
    id: "FRONT02-REGION-FIXTURE",
    path: "/regionen/beispiel",
    title: "Beispielregion",
    eyebrow: "Regionaler Hub · Strukturfixture",
    lead: "Dieses FRONT-02 Fixture demonstriert die organisationsbezogene Seitenstruktur ohne eine reale regionale Autorität oder Mitgliedschaft zu behaupten.",
    status: "specified",
    pack: "FRONT-02 / PACK-28",
    prerequisites: "Freigegebene Organisations- und Publikationsprojektion",
    kind: "standard",
    sections: [{ title: "Scope bleibt sichtbar", text: "Ein späterer Regionalhub zeigt die exakte freigegebene Körperschaft und trennt öffentliche Projektion von interner Organisationsautorität." }],
  },
  {
    id: "FRONT02-PAGE-005",
    path: "/personen",
    title: "Personen",
    eyebrow: "Öffentliche Rollen und Mandate",
    lead: "Diese zukünftige Übersicht ist keine Mitgliederdatenbank. Sie kann ausschließlich freigegebene öffentliche Personas anzeigen.",
    status: "planned",
    pack: "PACK-28 / WS-10",
    prerequisites: "Freigegebene öffentliche Personenrenditionen",
    kind: "standard",
    sections: [{ title: "Keine öffentliche Personenliste verfügbar", text: "Interne Mitglieder-, Kontakt- und Berechtigungsdaten werden nicht in eine öffentliche Ansicht übernommen." }],
  },
  {
    id: "FRONT02-PAGE-006",
    path: "/wahlen",
    title: "Wahlen",
    eyebrow: "Öffentliche Information · keine Stimmabgabe",
    lead: "Informationen über Wahlen und Kandidaturen können veröffentlicht werden. Die geheime Stimmabgabe gehört ausschließlich zum isolierten WS-03 Voting Client.",
    status: "not_activated",
    pack: "PACK-15 / PACK-16 / PACK-17",
    prerequisites: "Rechts-, Sicherheits-, Infrastruktur- und kryptographische Freigaben",
    kind: "voting",
    sections: [{ title: "Keine Wahlfunktion auf dieser Website", text: "Diese Oberfläche prüft keine Stimmberechtigung, nimmt keine Stimme entgegen und teilt keine Sitzung oder Speicher mit einem Voting Client." }],
  },
  {
    id: "FRONT02-PAGE-007",
    path: "/hilfe",
    title: "Hilfe",
    eyebrow: "Unterstützung in Ebenen",
    lead: "Hilfe beginnt mit verständlichen öffentlichen Informationen. Geschützte Vorgänge, Entscheidungen und Rückfragen werden nur im jeweils zuständigen Workspace behandelt.",
    status: "informational",
    pack: "FRONT-02 / PACK-18",
    prerequisites: "Versionierte Hilfeinhalte und zuständige Kontaktwege",
    kind: "standard",
    sections: [
      { title: "Öffentliche Hilfe", text: "Diese Seite erklärt den Status der Plattform, die getrennten Workspaces und sichere nächste Schritte." },
      { title: "Wenn etwas nicht verfügbar ist", text: "Ein Hinweis benennt den Zustand und verweist auf einen öffentlichen Kontakt- oder späteren zuständigen Supportweg; er erfindet keine Ticket- oder Fallnummer." },
    ],
  },
  {
    id: "FRONT02-PAGE-008",
    path: "/suche",
    title: "Suche",
    eyebrow: "Nur freigegebene öffentliche Inhalte",
    lead: "Die öffentliche Suche wird erst mit einem freigegebenen Index verbunden. Sie durchsucht keine internen Arbeitsbereiche und erweitert keine Berechtigungen.",
    status: "planned",
    pack: "PACK-12 / PACK-13 / WS-10",
    prerequisites: "Freigegebener öffentlicher Suchindex und Renditionsprüfung",
    kind: "standard",
    sections: [{ title: "Noch kein öffentlicher Suchindex verbunden", text: "Ein zukünftiges Ergebnis darf nur erscheinen, wenn die zugehörige freigegebene Rendition auch geöffnet werden darf." }],
  },
];

export const front02PageByPath = new Map(front02PublicPages.map((page) => [page.path, page]));
