#!/usr/bin/env python3
"""Check that required repository files and directories exist.

Usage:
    python scripts/check_repository.py

Exits with a non-zero status and prints every missing path if anything
required is absent. Run from anywhere; the repository root is resolved
relative to this script's location.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Required top-level files and directories, per CLAUDE-PACK-01 section 5
# ("Final repository structure"). Paths are relative to the repository
# root. This intentionally does not enumerate every possible file - it
# enumerates the files and directories the package definition requires to
# exist.
REQUIRED_PATHS: tuple[str, ...] = (
    # Root
    "README.md",
    "LICENSE",
    "SECURITY.md",
    "CONTRIBUTING.md",
    "CODEOWNERS",
    "CHANGELOG.md",
    "LOCAL_VERIFICATION.md",
    "Makefile",
    ".editorconfig",
    ".gitignore",
    ".pre-commit-config.yaml",
    "pyproject.toml",
    "uv.lock",
    "package.json",
    "package-lock.json",
    # GitHub
    ".github/workflows/ci.yml",
    ".github/pull_request_template.md",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/ISSUE_TEMPLATE/architecture_change.yml",
    # Docs: canonical
    "docs/canonical/README.md",
    "docs/canonical/TZ-00-domain-event-canon.md",
    "docs/canonical/canon-version.json",
    # Docs: architecture
    "docs/architecture/system-context.md",
    "docs/architecture/service-boundaries.md",
    "docs/architecture/data-ownership.md",
    # Docs: adr
    "docs/adr/README.md",
    "docs/adr/ADR-000-template.md",
    "docs/adr/ADR-001-repository-strategy.md",
    "docs/adr/ADR-002-identity-participation-separation.md",
    "docs/adr/ADR-003-append-only-audit-hash-chain.md",
    "docs/adr/ADR-004-reason-code-registry.md",
    "docs/adr/ADR-005-pack-03-service-decomposition.md",
    "docs/adr/ADR-006-pack-03-reason-code-additions.md",
    "docs/adr/ADR-008-pack-03-pack-02-integration-boundary.md",
    "docs/adr/ADR-009-voting-delegation-quorum-defaults.md",
    "docs/adr/ADR-010-ballot-challenge-window-canon-addition.md",
    "docs/adr/ADR-011-pack-04-transparency-service-decomposition.md",
    "docs/adr/ADR-012-pack-04-cross-pack-read-boundary.md",
    "docs/adr/ADR-013-canon-0.3.0-transparency-context-additions.md",
    "docs/adr/ADR-014-pack-04-reason-code-additions.md",
    "docs/adr/ADR-015-disclosure-redaction-lobby-log-defaults.md",
    "docs/adr/ADR-016-pack-05-governance-service-decomposition.md",
    "docs/adr/ADR-017-pack-05-cross-pack-boundary.md",
    "docs/adr/ADR-018-canon-0.4.0-governance-context-additions.md",
    "docs/adr/ADR-019-pack-05-reason-code-additions.md",
    "docs/adr/ADR-020-pack-05-authority-roles-challenge-lifecycle.md",
    "docs/adr/ADR-021-pack-06-ai-processing-service-decomposition.md",
    "docs/adr/ADR-022-pack-06-cross-pack-boundary.md",
    "docs/adr/ADR-023-canon-0.5.0-ai-processing-context-additions.md",
    "docs/adr/ADR-024-pack-06-reason-code-additions.md",
    "docs/adr/ADR-025-pack-06-use-policy-redaction-providers-disclosure.md",
    # Docs: ADRs — PACK-09 (Compliance, Records Governance & Legal
    # Workflows). PACK-07's and PACK-08's own ADRs (ADR-026 through
    # ADR-037) are present in docs/adr/ but were never added to this list
    # by those rounds; that pre-existing gap is left untouched here rather
    # than silently widened, and is recorded in
    # docs/review/KNOWN_LIMITATIONS.md.
    "docs/adr/ADR-038-pack-09-compliance-service-decomposition.md",
    "docs/adr/ADR-043-official-notice-legal-effect-trust-boundary.md",
    "docs/handover/PACK-09-KNOWN-LIMITATIONS.md",
    "docs/adr/ADR-039-record-retention-and-legal-hold.md",
    "docs/adr/ADR-040-processing-registry-and-data-catalog.md",
    "docs/adr/ADR-041-governed-procedural-cases-and-deadlines.md",
    "docs/adr/ADR-042-party-arbitration-independence.md",
    # FRONT-00 frontend foundation candidate
    "docs/adr/ADR-044-shared-frontend-source-runtime-isolation.md",
    "docs/adr/ADR-045-existing-visual-baseline-preservation.md",
    "docs/adr/ADR-046-voting-client-origin-and-build-isolation.md",
    "docs/adr/ADR-047-frontend-browser-storage-policy.md",
    "docs/frontend/FRONT-00-SPECIFICATION.md",
    "docs/frontend/FRONT-00-IMPLEMENTATION.md",
    "docs/frontend/FRONT-00-COMPONENT-CATALOG.md",
    "docs/frontend/FRONT-00-DESIGN-PRESERVATION.md",
    "docs/frontend/FRONT-00-WORKSPACE-ISOLATION.md",
    "docs/frontend/FRONT-00-STORAGE-POLICY.md",
    "docs/frontend/FRONT-00-TELEMETRY-POLICY.md",
    "docs/frontend/FRONT-00-ACCESSIBILITY.md",
    "docs/frontend/FRONT-00-VISUAL-REGRESSION.md",
    "docs/frontend/FRONT-00-ACCEPTANCE-MATRIX.md",
    "docs/frontend/FRONT-00-KNOWN-LIMITATIONS.md",
    "docs/frontend/FRONT-00-PAGE-INVENTORY.md",
    "docs/frontend/FRONT-00-PAGE-INVENTORY.csv",
    "docs/handover/FRONT-00-CANDIDATE-REPORT.md",
    "frontend/web-shell/components/foundation.tsx",
    "frontend/web-shell/components/DialogExample.tsx",
    "frontend/web-shell/foundation/types.ts",
    "frontend/web-shell/foundation/workspaces.ts",
    "frontend/web-shell/foundation/routes.ts",
    "frontend/web-shell/foundation/storage-policy.ts",
    "frontend/web-shell/foundation/telemetry-policy.ts",
    "frontend/web-shell/app/foundation/page.tsx",
    "frontend/web-shell/app/foundation/examples/[kind]/page.tsx",
    "frontend/web-shell/tests/front00.test.ts",
    "scripts/generate_front00_inventory.py",
    # Docs: development
    "docs/development/local-development.md",
    "docs/development/repository-rules.md",
    "docs/development/new-module-guide.md",
    # Docs: review
    "docs/review/OPEN_QUESTIONS.md",
    "docs/review/KNOWN_LIMITATIONS.md",
    "docs/review/PACK-05-OWNER-DECISIONS.md",
    "docs/review/PACK-06-OWNER-DECISIONS.md",
    # Docs: handover
    "docs/handover/PACK-01-REPORT.md",
    "docs/handover/PACK-02-REPORT.md",
    "docs/handover/PACK-03-REPORT.md",
    "docs/handover/PACK-03-SPEC.md",
    "docs/handover/PACK-04-SPEC.md",
    "docs/handover/PACK-04-REPORT.md",
    "docs/handover/PACK-05-SPEC.md",
    "docs/handover/PACK-05-REPORT.md",
    "docs/handover/PACK-06-SPEC.md",
    "docs/handover/PACK-06-REPORT.md",
    "docs/handover/PACK-08-SPEC-REPORT.md",
    "docs/handover/PACK-08-CANON-AMENDMENT-REPORT.md",
    "docs/handover/PACK-08-IMPLEMENTATION-REPORT.md",
    "docs/handover/PACK-09-IMPLEMENTATION-REPORT.md",
    # Docs: packs (PACK-08 IMPLEMENTATION ROUND)
    "docs/packs/PACK-08-SPECIFICATION.md",
    "docs/packs/PACK-08-MIGRATION-MATRIX.md",
    "docs/packs/PACK-08-OPEN-DECISIONS.md",
    "docs/packs/PACK-08-ROLE-SCOPE-MIGRATION-TABLE.md",
    "docs/packs/PACK-08-IMPLEMENTATION.md",
    "docs/packs/PACK-09-SPECIFICATION.md",
    "docs/packs/PACK-09-IMPLEMENTATION.md",
    # Contracts
    "contracts/README.md",
    "contracts/openapi",
    "contracts/events",
    "contracts/schemas",
    "contracts/reason-codes/README.md",
    "contracts/fixtures",
    # Contracts: PACK-02 reason codes registry
    "contracts/reason-codes/pack-02.yml",
    # Contracts: PACK-02 JSON Schemas
    "contracts/schemas/event-envelope.schema.json",
    "contracts/schemas/account.schema.json",
    "contracts/schemas/identity-record.schema.json",
    "contracts/schemas/eligibility-rule.schema.json",
    "contracts/schemas/eligibility-decision.schema.json",
    "contracts/schemas/eligibility-snapshot.schema.json",
    "contracts/schemas/participation-credential.schema.json",
    "contracts/schemas/audit-event.schema.json",
    # Contracts: PACK-02 event payload schemas
    "contracts/events/account-event-payload.v1.schema.json",
    "contracts/events/identity-event-payload.v1.schema.json",
    "contracts/events/eligibility-evaluated-payload.v1.schema.json",
    "contracts/events/eligibility-snapshot-created-payload.v1.schema.json",
    "contracts/events/credential-issued-or-revoked-payload.v1.schema.json",
    "contracts/events/credential-validation-failed-payload.v1.schema.json",
    # Contracts: PACK-02 OpenAPI
    "contracts/openapi/pack-02.yaml",
    # Contracts: PACK-03 reason codes registry
    "contracts/reason-codes/pack-03.yml",
    # Contracts: PACK-03 JSON Schemas
    "contracts/schemas/initiative.schema.json",
    "contracts/schemas/initiative-version.schema.json",
    "contracts/schemas/support-record.schema.json",
    "contracts/schemas/amendment.schema.json",
    "contracts/schemas/source-record.schema.json",
    "contracts/schemas/discussion.schema.json",
    "contracts/schemas/contribution.schema.json",
    "contracts/schemas/moderation-case.schema.json",
    "contracts/schemas/moderation-decision.schema.json",
    "contracts/schemas/appeal.schema.json",
    "contracts/schemas/ballot.schema.json",
    "contracts/schemas/ballot-option.schema.json",
    "contracts/schemas/vote-envelope.schema.json",
    "contracts/schemas/vote-receipt.schema.json",
    "contracts/schemas/tally.schema.json",
    "contracts/schemas/result-publication.schema.json",
    "contracts/schemas/delegation.schema.json",
    "contracts/schemas/delegation-snapshot.schema.json",
    # Contracts: PACK-03 event payload schemas
    "contracts/events/initiative-status-changed-payload.v1.schema.json",
    "contracts/events/initiative-version-created-payload.v1.schema.json",
    "contracts/events/initiative-support-changed-payload.v1.schema.json",
    "contracts/events/amendment-status-changed-payload.v1.schema.json",
    "contracts/events/discussion-status-changed-payload.v1.schema.json",
    "contracts/events/contribution-status-changed-payload.v1.schema.json",
    "contracts/events/contribution-flagged-payload.v1.schema.json",
    "contracts/events/moderation-case-status-changed-payload.v1.schema.json",
    "contracts/events/moderation-decision-payload.v1.schema.json",
    "contracts/events/appeal-status-changed-payload.v1.schema.json",
    "contracts/events/ballot-status-changed-payload.v1.schema.json",
    "contracts/events/vote-envelope-status-changed-payload.v1.schema.json",
    "contracts/events/vote-rejected-payload.v1.schema.json",
    "contracts/events/vote-superseded-payload.v1.schema.json",
    "contracts/events/tally-status-changed-payload.v1.schema.json",
    "contracts/events/result-published-payload.v1.schema.json",
    "contracts/events/delegation-status-changed-payload.v1.schema.json",
    "contracts/events/delegation-snapshot-created-payload.v1.schema.json",
    # Contracts: PACK-03 OpenAPI
    "contracts/openapi/pack-03.yaml",
    # Contracts: PACK-04 reason codes registry
    "contracts/reason-codes/pack-04.yml",
    # Contracts: PACK-04 JSON Schemas
    "contracts/schemas/public-ledger-entry.schema.json",
    "contracts/schemas/audit-export-package.schema.json",
    "contracts/schemas/disclosure-policy.schema.json",
    "contracts/schemas/lobby-log-entry.schema.json",
    # Contracts: PACK-04 event payload schemas
    "contracts/events/transparency-ledger-entry-payload.v1.schema.json",
    "contracts/events/transparency-audit-export-payload.v1.schema.json",
    "contracts/events/transparency-disclosure-policy-payload.v1.schema.json",
    "contracts/events/transparency-lobby-log-entry-payload.v1.schema.json",
    # Contracts: PACK-04 OpenAPI
    "contracts/openapi/pack-04.yaml",
    # Contracts: PACK-05 reason codes registry
    "contracts/reason-codes/pack-05.yml",
    # Contracts: PACK-05 JSON Schemas
    "contracts/schemas/role-assignment.schema.json",
    "contracts/schemas/governance-policy.schema.json",
    "contracts/schemas/governance-decision.schema.json",
    "contracts/schemas/technical-challenge.schema.json",
    # Contracts: PACK-05 event payload schemas
    "contracts/events/governance-role-assignment-payload.v1.schema.json",
    "contracts/events/governance-policy-payload.v1.schema.json",
    "contracts/events/governance-decision-payload.v1.schema.json",
    "contracts/events/governance-technical-challenge-payload.v1.schema.json",
    # Contracts: PACK-05 OpenAPI
    "contracts/openapi/pack-05.yaml",
    # Contracts: PACK-06 reason codes registry
    "contracts/reason-codes/pack-06.yml",
    # Contracts: PACK-06 JSON Schemas
    "contracts/schemas/ai-processing-record.schema.json",
    "contracts/schemas/ai-disclosure-package.schema.json",
    # Contracts: PACK-06 event payload schemas
    "contracts/events/ai-processing-record-payload.v1.schema.json",
    # Contracts: PACK-06 OpenAPI
    "contracts/openapi/pack-06.yaml",
    # Contracts: PACK-07 reason codes registry
    "contracts/reason-codes/pack-07.yml",
    # Contracts: PACK-07 JSON Schemas
    "contracts/schemas/participant-eligibility-policy.schema.json",
    "contracts/schemas/process-eligibility-policy.schema.json",
    "contracts/schemas/step-up-authentication-requirement.schema.json",
    "contracts/schemas/digital-decision.schema.json",
    "contracts/schemas/assembly-decision.schema.json",
    "contracts/schemas/party-membership-eligibility-policy.schema.json",
    "contracts/schemas/membership.schema.json",
    "contracts/schemas/membership-application.schema.json",
    "contracts/schemas/affiliation-declaration.schema.json",
    "contracts/schemas/conflict-assessment.schema.json",
    # Contracts: PACK-07 event payload schemas
    "contracts/events/participation-rights-derived-payload.v1.schema.json",
    "contracts/events/formal-confirmation-requested-payload.v1.schema.json",
    "contracts/events/formal-confirmation-recorded-payload.v1.schema.json",
    "contracts/events/authentication-context-event-payload.v1.schema.json",
    "contracts/events/membership-application-submitted-payload.v1.schema.json",
    "contracts/events/membership-eligibility-evaluated-payload.v1.schema.json",
    "contracts/events/membership-decision-recorded-payload.v1.schema.json",
    "contracts/events/membership-activated-payload.v1.schema.json",
    "contracts/events/membership-suspended-payload.v1.schema.json",
    "contracts/events/affiliation-declared-payload.v1.schema.json",
    "contracts/events/conflict-assessment-opened-payload.v1.schema.json",
    "contracts/events/conflict-decision-recorded-payload.v1.schema.json",
    # Contracts: PACK-07 OpenAPI
    "contracts/openapi/pack-07.yaml",
    # Contracts: PACK-08 reason codes registry
    "contracts/reason-codes/pack-08.yml",
    # Contracts: PACK-08 JSON Schemas
    "contracts/schemas/organization.schema.json",
    "contracts/schemas/organizational-unit.schema.json",
    "contracts/schemas/civic-space.schema.json",
    "contracts/schemas/organizational-relation.schema.json",
    "contracts/schemas/organizational-authority.schema.json",
    # Contracts: PACK-08 event payload schemas
    "contracts/events/organization-status-payload.v1.schema.json",
    "contracts/events/organizational-relation-created-payload.v1.schema.json",
    "contracts/events/organizational-relation-ended-payload.v1.schema.json",
    "contracts/events/organizational-authority-assigned-payload.v1.schema.json",
    "contracts/events/organizational-authority-revoked-payload.v1.schema.json",
    "contracts/events/regional-scope-access-granted-payload.v1.schema.json",
    "contracts/events/regional-scope-access-revoked-payload.v1.schema.json",
    # Contracts: PACK-08 OpenAPI
    "contracts/openapi/pack-08.yaml",
    # Contracts: PACK-09 reason codes registry
    "contracts/reason-codes/pack-09.yml",
    # Contracts: PACK-09 JSON Schemas (ADR-038 through ADR-042)
    "contracts/schemas/retention-policy.schema.json",
    "contracts/schemas/retention-start-event.schema.json",
    "contracts/schemas/governed-record.schema.json",
    "contracts/schemas/legal-hold.schema.json",
    "contracts/schemas/destruction-authorization.schema.json",
    "contracts/schemas/destruction-evidence.schema.json",
    "contracts/schemas/data-asset.schema.json",
    "contracts/schemas/processing-activity.schema.json",
    "contracts/schemas/procedural-case.schema.json",
    "contracts/schemas/case-decision.schema.json",
    "contracts/schemas/conflict-of-interest-declaration.schema.json",
    "contracts/schemas/deadline-definition.schema.json",
    "contracts/schemas/procedural-deadline.schema.json",
    "contracts/schemas/data-subject-request.schema.json",
    "contracts/schemas/cross-scope-authority-grant.schema.json",
    # Contracts: PACK-09 event payload schemas
    "contracts/events/governed-record-retention-started-payload.v1.schema.json",
    "contracts/events/governed-record-disposal-authorized-payload.v1.schema.json",
    "contracts/events/governed-record-destroyed-payload.v1.schema.json",
    "contracts/events/legal-hold-status-changed-payload.v1.schema.json",
    "contracts/events/processing-activity-status-changed-payload.v1.schema.json",
    "contracts/events/procedural-case-status-changed-payload.v1.schema.json",
    "contracts/events/procedural-deadline-state-changed-payload.v1.schema.json",
    "contracts/events/data-subject-request-status-changed-payload.v1.schema.json",
    # Contracts: PACK-09 OpenAPI
    "contracts/openapi/pack-09.yaml",
    # Services (placeholder)
    "services/README.md",
    # Services: account-service
    "services/account-service/README.md",
    "services/account-service/pyproject.toml",
    "services/account-service/src/epd2_account_service/__init__.py",
    "services/account-service/src/epd2_account_service/domain.py",
    "services/account-service/src/epd2_account_service/application.py",
    "services/account-service/src/epd2_account_service/events.py",
    "services/account-service/src/epd2_account_service/exceptions.py",
    "services/account-service/src/epd2_account_service/storage.py",
    "services/account-service/tests/test_domain.py",
    "services/account-service/tests/test_application.py",
    # Services: identity-service
    "services/identity-service/README.md",
    "services/identity-service/pyproject.toml",
    "services/identity-service/src/epd2_identity_service/__init__.py",
    "services/identity-service/src/epd2_identity_service/domain.py",
    "services/identity-service/src/epd2_identity_service/application.py",
    "services/identity-service/src/epd2_identity_service/events.py",
    "services/identity-service/src/epd2_identity_service/exceptions.py",
    "services/identity-service/src/epd2_identity_service/storage.py",
    "services/identity-service/tests/test_domain.py",
    "services/identity-service/tests/test_application.py",
    "services/identity-service/tests/test_application_pack07.py",
    # Services: eligibility-service
    "services/eligibility-service/README.md",
    "services/eligibility-service/pyproject.toml",
    "services/eligibility-service/src/epd2_eligibility_service/__init__.py",
    "services/eligibility-service/src/epd2_eligibility_service/domain.py",
    "services/eligibility-service/src/epd2_eligibility_service/application.py",
    "services/eligibility-service/src/epd2_eligibility_service/events.py",
    "services/eligibility-service/src/epd2_eligibility_service/exceptions.py",
    "services/eligibility-service/src/epd2_eligibility_service/storage.py",
    "services/eligibility-service/tests/test_domain.py",
    "services/eligibility-service/tests/test_application.py",
    "services/eligibility-service/tests/test_application_pack07.py",
    # Services: credential-service
    "services/credential-service/README.md",
    "services/credential-service/pyproject.toml",
    "services/credential-service/src/epd2_credential_service/__init__.py",
    "services/credential-service/src/epd2_credential_service/domain.py",
    "services/credential-service/src/epd2_credential_service/application.py",
    "services/credential-service/src/epd2_credential_service/events.py",
    "services/credential-service/src/epd2_credential_service/exceptions.py",
    "services/credential-service/src/epd2_credential_service/storage.py",
    "services/credential-service/src/epd2_credential_service/validation.py",
    "services/credential-service/tests/test_domain.py",
    "services/credential-service/tests/test_application.py",
    "services/credential-service/tests/test_storage.py",
    "services/credential-service/tests/test_validation.py",
    # Services: initiative-service
    "services/initiative-service/README.md",
    "services/initiative-service/pyproject.toml",
    "services/initiative-service/src/epd2_initiative_service/__init__.py",
    "services/initiative-service/src/epd2_initiative_service/domain.py",
    "services/initiative-service/src/epd2_initiative_service/application.py",
    "services/initiative-service/src/epd2_initiative_service/events.py",
    "services/initiative-service/src/epd2_initiative_service/exceptions.py",
    "services/initiative-service/src/epd2_initiative_service/storage.py",
    "services/initiative-service/tests/test_domain.py",
    "services/initiative-service/tests/test_application.py",
    "services/initiative-service/tests/test_storage.py",
    # Services: deliberation-service
    "services/deliberation-service/README.md",
    "services/deliberation-service/pyproject.toml",
    "services/deliberation-service/src/epd2_deliberation_service/__init__.py",
    "services/deliberation-service/src/epd2_deliberation_service/domain.py",
    "services/deliberation-service/src/epd2_deliberation_service/application.py",
    "services/deliberation-service/src/epd2_deliberation_service/events.py",
    "services/deliberation-service/src/epd2_deliberation_service/exceptions.py",
    "services/deliberation-service/src/epd2_deliberation_service/storage.py",
    "services/deliberation-service/tests/test_domain.py",
    "services/deliberation-service/tests/test_application.py",
    "services/deliberation-service/tests/test_storage.py",
    # Services: moderation-service
    "services/moderation-service/README.md",
    "services/moderation-service/pyproject.toml",
    "services/moderation-service/src/epd2_moderation_service/__init__.py",
    "services/moderation-service/src/epd2_moderation_service/domain.py",
    "services/moderation-service/src/epd2_moderation_service/application.py",
    "services/moderation-service/src/epd2_moderation_service/events.py",
    "services/moderation-service/src/epd2_moderation_service/exceptions.py",
    "services/moderation-service/src/epd2_moderation_service/storage.py",
    "services/moderation-service/tests/test_domain.py",
    "services/moderation-service/tests/test_application.py",
    "services/moderation-service/tests/test_storage.py",
    # Services: voting-service
    "services/voting-service/README.md",
    "services/voting-service/pyproject.toml",
    "services/voting-service/src/epd2_voting_service/__init__.py",
    "services/voting-service/src/epd2_voting_service/domain.py",
    "services/voting-service/src/epd2_voting_service/application.py",
    "services/voting-service/src/epd2_voting_service/events.py",
    "services/voting-service/src/epd2_voting_service/exceptions.py",
    "services/voting-service/src/epd2_voting_service/storage.py",
    "services/voting-service/tests/test_domain.py",
    "services/voting-service/tests/test_application.py",
    "services/voting-service/tests/test_storage.py",
    # Services: tally-service
    "services/tally-service/README.md",
    "services/tally-service/pyproject.toml",
    "services/tally-service/src/epd2_tally_service/__init__.py",
    "services/tally-service/src/epd2_tally_service/domain.py",
    "services/tally-service/src/epd2_tally_service/application.py",
    "services/tally-service/src/epd2_tally_service/events.py",
    "services/tally-service/src/epd2_tally_service/exceptions.py",
    "services/tally-service/src/epd2_tally_service/storage.py",
    "services/tally-service/tests/test_domain.py",
    "services/tally-service/tests/test_application.py",
    "services/tally-service/tests/test_storage.py",
    # Services: delegation-service
    "services/delegation-service/README.md",
    "services/delegation-service/pyproject.toml",
    "services/delegation-service/src/epd2_delegation_service/__init__.py",
    "services/delegation-service/src/epd2_delegation_service/domain.py",
    "services/delegation-service/src/epd2_delegation_service/application.py",
    "services/delegation-service/src/epd2_delegation_service/events.py",
    "services/delegation-service/src/epd2_delegation_service/exceptions.py",
    "services/delegation-service/src/epd2_delegation_service/storage.py",
    "services/delegation-service/tests/test_domain.py",
    "services/delegation-service/tests/test_application.py",
    "services/delegation-service/tests/test_storage.py",
    # Services: transparency-service
    "services/transparency-service/README.md",
    "services/transparency-service/pyproject.toml",
    "services/transparency-service/src/epd2_transparency_service/__init__.py",
    "services/transparency-service/src/epd2_transparency_service/domain.py",
    "services/transparency-service/src/epd2_transparency_service/application.py",
    "services/transparency-service/src/epd2_transparency_service/events.py",
    "services/transparency-service/src/epd2_transparency_service/exceptions.py",
    "services/transparency-service/src/epd2_transparency_service/storage.py",
    "services/transparency-service/tests/test_domain.py",
    "services/transparency-service/tests/test_application.py",
    "services/transparency-service/tests/test_storage.py",
    # Services: governance-service
    "services/governance-service/README.md",
    "services/governance-service/pyproject.toml",
    "services/governance-service/src/epd2_governance_service/__init__.py",
    "services/governance-service/src/epd2_governance_service/domain.py",
    "services/governance-service/src/epd2_governance_service/application.py",
    "services/governance-service/src/epd2_governance_service/events.py",
    "services/governance-service/src/epd2_governance_service/exceptions.py",
    "services/governance-service/src/epd2_governance_service/storage.py",
    "services/governance-service/src/epd2_governance_service/bootstrap.py",
    "services/governance-service/tests/test_domain.py",
    "services/governance-service/tests/test_application.py",
    "services/governance-service/tests/test_storage.py",
    "services/governance-service/tests/test_bootstrap.py",
    # Services: ai-processing-service
    "services/ai-processing-service/README.md",
    "services/ai-processing-service/pyproject.toml",
    "services/ai-processing-service/src/epd2_ai_processing_service/__init__.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/domain.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/application.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/events.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/exceptions.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/storage.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/provider.py",
    "services/ai-processing-service/src/epd2_ai_processing_service/redaction.py",
    "services/ai-processing-service/tests/test_domain.py",
    "services/ai-processing-service/tests/test_application.py",
    "services/ai-processing-service/tests/test_storage.py",
    # Services: audit-core
    "services/audit-core/README.md",
    "services/audit-core/pyproject.toml",
    "services/audit-core/src/epd2_audit_core/__init__.py",
    "services/audit-core/src/epd2_audit_core/domain.py",
    "services/audit-core/src/epd2_audit_core/application.py",
    "services/audit-core/src/epd2_audit_core/exceptions.py",
    "services/audit-core/src/epd2_audit_core/hash_chain.py",
    "services/audit-core/src/epd2_audit_core/storage.py",
    "services/audit-core/tests/test_domain.py",
    "services/audit-core/tests/test_application.py",
    "services/audit-core/tests/test_hash_chain.py",
    "services/audit-core/tests/test_storage.py",
    # Services: membership-service (PACK-07's one wholly new service)
    "services/membership-service/README.md",
    "services/membership-service/pyproject.toml",
    "services/membership-service/src/epd2_membership_service/__init__.py",
    "services/membership-service/src/epd2_membership_service/domain.py",
    "services/membership-service/src/epd2_membership_service/application.py",
    "services/membership-service/src/epd2_membership_service/events.py",
    "services/membership-service/src/epd2_membership_service/exceptions.py",
    "services/membership-service/src/epd2_membership_service/storage.py",
    "services/membership-service/tests/test_domain.py",
    "services/membership-service/tests/test_application.py",
    "services/membership-service/tests/test_storage.py",
    # Services: organization-service (PACK-08's one wholly new service)
    "services/organization-service/README.md",
    "services/organization-service/pyproject.toml",
    "services/organization-service/src/epd2_organization_service/__init__.py",
    "services/organization-service/src/epd2_organization_service/domain.py",
    "services/organization-service/src/epd2_organization_service/application.py",
    "services/organization-service/src/epd2_organization_service/events.py",
    "services/organization-service/src/epd2_organization_service/exceptions.py",
    "services/organization-service/src/epd2_organization_service/storage.py",
    "services/organization-service/tests/test_domain.py",
    "services/organization-service/tests/test_application.py",
    "services/organization-service/tests/test_storage.py",
    # Services: compliance-service (PACK-09's one wholly new service)
    "services/compliance-service/README.md",
    "services/compliance-service/pyproject.toml",
    "services/compliance-service/src/epd2_compliance_service/__init__.py",
    "services/compliance-service/src/epd2_compliance_service/domain.py",
    "services/compliance-service/src/epd2_compliance_service/application.py",
    "services/compliance-service/src/epd2_compliance_service/events.py",
    "services/compliance-service/src/epd2_compliance_service/exceptions.py",
    "services/compliance-service/src/epd2_compliance_service/storage.py",
    "services/compliance-service/tests/test_domain.py",
    "services/compliance-service/tests/test_application.py",
    "services/compliance-service/tests/test_storage.py",
    # compliance-service, Architecture & Domain Framework 0.8.1 additions
    # (same 0.9.0 round): the legal-case substrate, the official-notice
    # trust boundary, data-protection governance, and the stable typed
    # references PACK-09 publishes to PACK-10/11/19/21-24.
    "services/compliance-service/src/epd2_compliance_service/casework.py",
    "services/compliance-service/src/epd2_compliance_service/notices.py",
    "services/compliance-service/src/epd2_compliance_service/dataprotection.py",
    "services/compliance-service/src/epd2_compliance_service/references.py",
    "services/compliance-service/tests/test_casework.py",
    "services/compliance-service/tests/test_notices.py",
    "services/compliance-service/tests/test_dataprotection.py",
    "services/compliance-service/tests/test_framework_application.py",
    # PACK-09 Framework 0.8.1 entity schemas
    "contracts/schemas/legal-case.schema.json",
    "contracts/schemas/jurisdiction-determination.schema.json",
    "contracts/schemas/case-party.schema.json",
    "contracts/schemas/representation-mandate.schema.json",
    "contracts/schemas/filing.schema.json",
    "contracts/schemas/hearing.schema.json",
    "contracts/schemas/interim-measure.schema.json",
    "contracts/schemas/procedural-decision.schema.json",
    "contracts/schemas/remedy.schema.json",
    "contracts/schemas/recusal-record.schema.json",
    "contracts/schemas/replacement-assignment.schema.json",
    "contracts/schemas/official-notice.schema.json",
    "contracts/schemas/service-attempt.schema.json",
    "contracts/schemas/notice-effect-decision.schema.json",
    "contracts/schemas/deadline-trigger.schema.json",
    "contracts/schemas/record-class.schema.json",
    "contracts/schemas/hold-propagation-record.schema.json",
    "contracts/schemas/dpia-requirement-determination.schema.json",
    "contracts/schemas/data-protection-impact-assessment.schema.json",
    "contracts/schemas/processing-activation-decision.schema.json",
    "contracts/schemas/transfer-assessment.schema.json",
    "contracts/schemas/consent-withdrawal-record.schema.json",
    # PACK-09 Framework 0.8.1 event payload schemas
    "contracts/events/legal-case-opened-payload.v1.schema.json",
    "contracts/events/legal-case-status-changed-payload.v1.schema.json",
    "contracts/events/legal-case-reopened-payload.v1.schema.json",
    "contracts/events/jurisdiction-determined-payload.v1.schema.json",
    "contracts/events/jurisdiction-challenged-payload.v1.schema.json",
    "contracts/events/jurisdiction-transferred-payload.v1.schema.json",
    "contracts/events/case-party-registered-payload.v1.schema.json",
    "contracts/events/representation-registered-payload.v1.schema.json",
    "contracts/events/representation-revoked-payload.v1.schema.json",
    "contracts/events/filing-received-payload.v1.schema.json",
    "contracts/events/filing-admissibility-decided-payload.v1.schema.json",
    "contracts/events/filing-superseded-payload.v1.schema.json",
    "contracts/events/hearing-scheduled-payload.v1.schema.json",
    "contracts/events/hearing-rescheduled-payload.v1.schema.json",
    "contracts/events/hearing-cancelled-payload.v1.schema.json",
    "contracts/events/hearing-completed-payload.v1.schema.json",
    "contracts/events/interim-measure-decided-payload.v1.schema.json",
    "contracts/events/procedural-decision-issued-payload.v1.schema.json",
    "contracts/events/decision-effect-changed-payload.v1.schema.json",
    "contracts/events/decision-finality-changed-payload.v1.schema.json",
    "contracts/events/decision-enforceability-changed-payload.v1.schema.json",
    "contracts/events/remedy-registered-payload.v1.schema.json",
    "contracts/events/recusal-recorded-payload.v1.schema.json",
    "contracts/events/replacement-assigned-payload.v1.schema.json",
    "contracts/events/official-notice-issued-payload.v1.schema.json",
    "contracts/events/service-attempt-recorded-payload.v1.schema.json",
    "contracts/events/notice-effect-determined-payload.v1.schema.json",
    "contracts/events/deadline-triggered-payload.v1.schema.json",
    "contracts/events/record-class-registered-payload.v1.schema.json",
    "contracts/events/hold-propagation-registered-payload.v1.schema.json",
    "contracts/events/dpia-requirement-determined-payload.v1.schema.json",
    "contracts/events/dpia-status-changed-payload.v1.schema.json",
    "contracts/events/processing-activation-decided-payload.v1.schema.json",
    # PACK-09 Framework 0.8.1 contract tests and shared samples
    "tests/contract/_pack09_framework_samples.py",
    "tests/contract/test_ct00_01_pack09_framework_schema_validation.py",
    # Python packages
    "packages/python/README.md",
    "packages/python/epd2-core/README.md",
    "packages/python/epd2-core/pyproject.toml",
    "packages/python/epd2-core/src/epd2_core/__init__.py",
    "packages/python/epd2-core/src/epd2_core/version.py",
    "packages/python/epd2-core/src/epd2_core/identifiers.py",
    "packages/python/epd2-core/tests/test_version.py",
    "packages/python/epd2-core/tests/test_identifiers.py",
    # TypeScript packages
    "packages/typescript/README.md",
    "packages/typescript/epd2-types/README.md",
    "packages/typescript/epd2-types/package.json",
    "packages/typescript/epd2-types/tsconfig.json",
    "packages/typescript/epd2-types/src/index.ts",
    "packages/typescript/epd2-types/src/version.ts",
    "packages/typescript/epd2-types/tests/version.test.ts",
    # Frontend
    "frontend/README.md",
    "frontend/web-shell/README.md",
    "frontend/web-shell/package.json",
    "frontend/web-shell/next.config.ts",
    "frontend/web-shell/tsconfig.json",
    "frontend/web-shell/eslint.config.mjs",
    "frontend/web-shell/app/layout.tsx",
    "frontend/web-shell/app/page.tsx",
    "frontend/web-shell/tests/smoke.test.ts",
    # Frontend: PACK-08 /organizations read-only vertical slice
    "frontend/web-shell/app/organizations/data.ts",
    "frontend/web-shell/app/organizations/labels.ts",
    "frontend/web-shell/app/organizations/authorization.ts",
    "frontend/web-shell/app/organizations/Bilingual.tsx",
    "frontend/web-shell/app/organizations/AsOfSelector.tsx",
    "frontend/web-shell/app/organizations/page.tsx",
    "frontend/web-shell/app/organizations/[id]/page.tsx",
    "frontend/web-shell/app/organizations/dev-authorization-console/page.tsx",
    "frontend/web-shell/tests/organizations.test.ts",
    # Scripts
    "scripts/check_repository.py",
    "scripts/check_forbidden_files.py",
    "scripts/verify_versions.py",
    # Tests
    "tests/repository/test_required_files.py",
    "tests/repository/test_forbidden_paths.py",
    "tests/repository/test_version_consistency.py",
    "tests/repository/test_service_boundaries.py",
    "tests/repository/test_pack07_duplicated_logic_parity.py",
    # Tests: PACK-02 contract test suite
    "tests/contract/conftest.py",
    "tests/contract/_schema_helpers.py",
    "tests/contract/test_ct00_01_schema_validation.py",
    "tests/contract/test_ct00_01_pack07_schema_validation.py",
    "tests/contract/test_ct00_01_pack08_schema_validation.py",
    "tests/contract/test_ct00_02_unknown_status.py",
    "tests/contract/test_ct00_03_forbidden_transition.py",
    "tests/contract/test_ct00_04_event_idempotency.py",
    "tests/contract/test_ct00_05_unsupported_event_version.py",
    "tests/contract/test_ct00_06_missing_permission.py",
    "tests/contract/test_ct00_07_audit_creation.py",
    "tests/contract/test_ct00_08_identity_leakage.py",
    "tests/contract/test_ct00_09_vote_linkability.py",
    "tests/contract/test_ct00_10_rule_freeze.py",
    "tests/contract/test_ct00_11_ai_human_control.py",
    "tests/contract/test_ct00_12_emergency_stop_not_applicable.py",
    "tests/contract/test_state_transitions.py",
    "tests/contract/test_audit.py",
    "tests/contract/test_reason_codes_registry.py",
    "tests/contract/test_openapi_contract.py",
    "tests/contract/test_property_based.py",
    # Services: finance-service (PACK-10's one wholly new service, canon
    # 0.8.0 section 19f). Every module is listed by name rather than the
    # directory alone, so removing one - the storage ports, say, or the
    # publication-safe projections - fails here instead of silently
    # shrinking the service.
    "services/finance-service/README.md",
    "services/finance-service/pyproject.toml",
    "services/finance-service/src/epd2_finance_service/__init__.py",
    "services/finance-service/src/epd2_finance_service/exceptions.py",
    "services/finance-service/src/epd2_finance_service/domain.py",
    "services/finance-service/src/epd2_finance_service/authorization.py",
    "services/finance-service/src/epd2_finance_service/ledger.py",
    "services/finance-service/src/epd2_finance_service/records.py",
    "services/finance-service/src/epd2_finance_service/reporting.py",
    "services/finance-service/src/epd2_finance_service/events.py",
    "services/finance-service/src/epd2_finance_service/references.py",
    "services/finance-service/src/epd2_finance_service/storage.py",
    "services/finance-service/src/epd2_finance_service/projections.py",
    "services/finance-service/src/epd2_finance_service/application.py",
    "services/finance-service/tests/test_domain.py",
    "services/finance-service/tests/test_authorization.py",
    "services/finance-service/tests/test_ledger.py",
    "services/finance-service/tests/test_records.py",
    "services/finance-service/tests/test_reporting.py",
    "services/finance-service/tests/test_events.py",
    "services/finance-service/tests/test_references.py",
    "services/finance-service/tests/test_storage.py",
    "services/finance-service/tests/test_projections.py",
    "services/finance-service/tests/test_application.py",
    "services/finance-service/tests/test_privacy_boundary.py",
    # PACK-10 contracts and documentation
    "contracts/reason-codes/pack-10.yml",
    "docs/packs/PACK-10-IMPLEMENTATION.md",
    "docs/architecture/finance-service.md",
    "docs/architecture/finance-ledger-model.md",
    "docs/architecture/finance-reporting-lifecycle.md",
    "docs/architecture/finance-separation-of-duties.md",
    "docs/architecture/finance-publication-projection.md",
    "docs/contracts/finance-command-query-contracts.md",
    "docs/handover/PACK-10-IMPLEMENTATION-REPORT.md",
    # Services: document-service (PACK-11's one wholly new service,
    # FIR-ROADMAP-001 and FIR-INV-010; ADR-055 through ADR-060). Thirteen
    # modules in strict dependency order, each importing only from those
    # above it.
    "services/document-service/README.md",
    "services/document-service/pyproject.toml",
    "services/document-service/src/epd2_document_service/__init__.py",
    "services/document-service/src/epd2_document_service/exceptions.py",
    "services/document-service/src/epd2_document_service/domain.py",
    "services/document-service/src/epd2_document_service/versions.py",
    "services/document-service/src/epd2_document_service/authorization.py",
    "services/document-service/src/epd2_document_service/documents.py",
    "services/document-service/src/epd2_document_service/evidence.py",
    "services/document-service/src/epd2_document_service/determinations.py",
    "services/document-service/src/epd2_document_service/references.py",
    "services/document-service/src/epd2_document_service/events.py",
    "services/document-service/src/epd2_document_service/storage.py",
    "services/document-service/src/epd2_document_service/projections.py",
    "services/document-service/src/epd2_document_service/application.py",
    "services/document-service/tests/conftest.py",
    "services/document-service/tests/_builders.py",
    "services/document-service/tests/test_domain.py",
    "services/document-service/tests/test_versions.py",
    "services/document-service/tests/test_authorization.py",
    "services/document-service/tests/test_documents.py",
    "services/document-service/tests/test_evidence.py",
    "services/document-service/tests/test_determinations.py",
    "services/document-service/tests/test_references.py",
    "services/document-service/tests/test_events.py",
    "services/document-service/tests/test_storage.py",
    "services/document-service/tests/test_projections.py",
    "services/document-service/tests/test_application.py",
    "services/document-service/tests/test_privacy_boundary.py",
    # PACK-11 contracts and documentation
    "contracts/reason-codes/pack-11.yml",
    "contracts/schemas/governed-document.schema.json",
    "contracts/schemas/document-version.schema.json",
    "contracts/schemas/evidence-bundle.schema.json",
    "contracts/schemas/publication-rendition.schema.json",
    "docs/adr/ADR-055-pack-11-document-service-decomposition.md",
    "docs/adr/ADR-056-document-authority-separation-and-access.md",
    "docs/adr/ADR-057-immutable-document-versions-and-hash-linked-history.md",
    "docs/adr/ADR-058-evidence-provenance-custody-and-sealed-bundles.md",
    "docs/adr/ADR-059-governed-determinations-not-inferred.md",
    "docs/adr/ADR-060-document-publication-separation-and-projection-surface.md",
    "docs/packs/PACK-11-SPECIFICATION.md",
    "docs/packs/PACK-11-IMPLEMENTATION.md",
    "docs/packs/PACK-11-FIR-TRACEABILITY.md",
    "docs/packs/PACK-11-ACCEPTANCE-MATRIX.md",
    "docs/packs/PACK-11-CROSS-PACK-BOUNDARIES.md",
    "docs/packs/PACK-11-THREAT-MODEL.md",
    "docs/packs/PACK-11-OPEN-DECISIONS.md",
    "docs/architecture/document-service.md",
    "docs/architecture/document-version-integrity.md",
    "docs/contracts/document-command-query-contracts.md",
    "docs/handover/PACK-11-IMPLEMENTATION-REPORT.md",
    "docs/handover/PACK-11-KNOWN-LIMITATIONS.md",
    # PACK-12: privileged administration, authorization-aware search and
    # governed data export (FIR-ROADMAP-002, ADR-061 through ADR-068).
    "services/privileged-access-service/README.md",
    "services/privileged-access-service/pyproject.toml",
    "services/privileged-access-service/src/epd2_privileged_access_service/__init__.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/exceptions.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/domain.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/policy.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/classification.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/roles.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/access.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/breakglass.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/sessions.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/search.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/export.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/dlp.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/disclosure.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/references.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/events.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/storage.py",
    "services/privileged-access-service/src/epd2_privileged_access_service/application.py",
    "services/privileged-access-service/tests/conftest.py",
    "services/privileged-access-service/tests/_privileged_builders.py",
    "services/privileged-access-service/tests/test_domain.py",
    "services/privileged-access-service/tests/test_policy.py",
    "services/privileged-access-service/tests/test_roles.py",
    "services/privileged-access-service/tests/test_access.py",
    "services/privileged-access-service/tests/test_breakglass.py",
    "services/privileged-access-service/tests/test_sessions.py",
    "services/privileged-access-service/tests/test_search.py",
    "services/privileged-access-service/tests/test_export.py",
    "services/privileged-access-service/tests/test_dlp.py",
    "services/privileged-access-service/tests/test_disclosure.py",
    "services/privileged-access-service/tests/test_events.py",
    "services/privileged-access-service/tests/test_storage.py",
    "services/privileged-access-service/tests/test_application.py",
    "services/privileged-access-service/tests/test_application_flows.py",
    "contracts/reason-codes/pack-12.yml",
    # PACK-13: the production data plane and contract evolution reference
    # implementation (FIR-ROADMAP-003; ADR-069 through ADR-078). An
    # implementation CANDIDATE, not a PASS: every storage adapter in it is
    # in memory and no production infrastructure is deployed.
    "services/data-plane-service/README.md",
    "services/data-plane-service/pyproject.toml",
    "services/data-plane-service/src/epd2_data_plane_service/__init__.py",
    "services/data-plane-service/src/epd2_data_plane_service/exceptions.py",
    "services/data-plane-service/src/epd2_data_plane_service/domain.py",
    "services/data-plane-service/src/epd2_data_plane_service/concurrency.py",
    "services/data-plane-service/src/epd2_data_plane_service/idempotency.py",
    "services/data-plane-service/src/epd2_data_plane_service/canonicalization.py",
    "services/data-plane-service/src/epd2_data_plane_service/registry.py",
    "services/data-plane-service/src/epd2_data_plane_service/compatibility.py",
    "services/data-plane-service/src/epd2_data_plane_service/contracts.py",
    "services/data-plane-service/src/epd2_data_plane_service/migrations.py",
    "services/data-plane-service/src/epd2_data_plane_service/backfill.py",
    "services/data-plane-service/src/epd2_data_plane_service/outbox.py",
    "services/data-plane-service/src/epd2_data_plane_service/delivery.py",
    "services/data-plane-service/src/epd2_data_plane_service/projections.py",
    "services/data-plane-service/src/epd2_data_plane_service/integration.py",
    "services/data-plane-service/src/epd2_data_plane_service/retention.py",
    "services/data-plane-service/src/epd2_data_plane_service/privileged.py",
    "services/data-plane-service/src/epd2_data_plane_service/boundaries.py",
    "services/data-plane-service/src/epd2_data_plane_service/events.py",
    "services/data-plane-service/src/epd2_data_plane_service/storage.py",
    "services/data-plane-service/src/epd2_data_plane_service/application.py",
    "services/data-plane-service/src/epd2_data_plane_service/administration.py",
    "services/data-plane-service/tests/conftest.py",
    "services/data-plane-service/tests/_data_plane_builders.py",
    "services/data-plane-service/tests/test_domain.py",
    "services/data-plane-service/tests/test_concurrency.py",
    "services/data-plane-service/tests/test_idempotency.py",
    "services/data-plane-service/tests/test_canonicalization.py",
    "services/data-plane-service/tests/test_registry.py",
    "services/data-plane-service/tests/test_compatibility.py",
    "services/data-plane-service/tests/test_contracts.py",
    "services/data-plane-service/tests/test_migrations.py",
    "services/data-plane-service/tests/test_backfill.py",
    "services/data-plane-service/tests/test_outbox.py",
    "services/data-plane-service/tests/test_delivery.py",
    "services/data-plane-service/tests/test_projections.py",
    "services/data-plane-service/tests/test_integration.py",
    "services/data-plane-service/tests/test_retention.py",
    "services/data-plane-service/tests/test_privileged.py",
    "services/data-plane-service/tests/test_boundaries.py",
    "services/data-plane-service/tests/test_events.py",
    "services/data-plane-service/tests/test_storage.py",
    "services/data-plane-service/tests/test_data_plane_application.py",
    "services/data-plane-service/tests/test_administration.py",
    "contracts/reason-codes/pack-13.yml",
    "docs/adr/ADR-069-PRODUCTION-RELATIONAL-DATA-PLANE.md",
    "docs/adr/ADR-070-DOMAIN-DATA-OWNERSHIP.md",
    "docs/adr/ADR-071-TRANSACTIONAL-OUTBOX.md",
    "docs/adr/ADR-072-AT-LEAST-ONCE-DELIVERY-AND-IDEMPOTENT-CONSUMERS.md",
    "docs/adr/ADR-073-CANONICAL-SCHEMA-REGISTRY.md",
    "docs/adr/ADR-074-API-AND-EVENT-CONTRACT-EVOLUTION.md",
    "docs/adr/ADR-075-DATABASE-MIGRATION-DISCIPLINE.md",
    "docs/adr/ADR-076-PROJECTION-AND-READ-MODEL-GOVERNANCE.md",
    "docs/adr/ADR-077-CONCURRENCY-AND-IDEMPOTENCY.md",
    "docs/adr/ADR-078-DATA-PLANE-RETENTION-LEGAL-HOLD-AND-EVIDENCE.md",
    "docs/packs/PACK-13/PACK-13-SPECIFICATION.md",
    "docs/packs/PACK-13/PACK-13-ACCEPTANCE-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-FIR-COVERAGE-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-DATA-OWNERSHIP-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-EVENT-CATALOG.md",
    "docs/packs/PACK-13/PACK-13-EVENT-DELIVERY-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-MIGRATION-CONTROL-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-REASON-CODE-CATALOG.md",
    "docs/packs/PACK-13/PACK-13-SCHEMA-COMPATIBILITY-MATRIX.md",
    "docs/packs/PACK-13/PACK-13-THREAT-MODEL.md",
    "docs/packs/PACK-13/PACK-13-CANON-ASSESSMENT.md",
    "docs/handover/PACK-13-SPEC-ADR-REPORT.md",
    "docs/handover/PACK-13-IMPLEMENTATION-CANDIDATE-REPORT.md",
    "docs/handover/PACK-13-KNOWN-LIMITATIONS.md",
    "tests/repository/test_pack13_fir_matrix.py",
    "docs/adr/ADR-061-pack-12-privileged-role-separation.md",
    "docs/adr/ADR-062-pack-12-purpose-scoped-pam.md",
    "docs/adr/ADR-063-pack-12-break-glass-dual-control.md",
    "docs/adr/ADR-064-pack-12-authorization-aware-search.md",
    "docs/adr/ADR-065-pack-12-high-confidentiality-index-exclusion.md",
    "docs/adr/ADR-066-pack-12-governed-data-export.md",
    "docs/adr/ADR-067-pack-12-dlp-and-disclosure-control.md",
    "docs/adr/ADR-068-pack-12-privileged-session-evidence.md",
    "docs/packs/PACK-12/PACK-12-SPECIFICATION.md",
    "docs/packs/PACK-12/PACK-12-ROLE-SEPARATION-MATRIX.md",
    "docs/packs/PACK-12/PACK-12-DATA-SEARCH-EXPORT-MATRIX.md",
    "docs/packs/PACK-12/PACK-12-EVENT-CATALOG.md",
    "docs/packs/PACK-12/PACK-12-REASON-CODE-CATALOG.md",
    "docs/packs/PACK-12/PACK-12-THREAT-MODEL.md",
    "docs/packs/PACK-12/PACK-12-ACCEPTANCE-MATRIX.md",
    "docs/packs/PACK-12/PACK-12-CANON-ASSESSMENT.md",
    "docs/packs/PACK-12/PACK-12-FIR-COVERAGE-MATRIX.md",
    "docs/handover/PACK-12-SPEC-ADR-REPORT.md",
    "docs/handover/PACK-12-IMPLEMENTATION-CANDIDATE-REPORT.md",
    "docs/handover/PACK-12-KNOWN-LIMITATIONS.md",
    # The master future-implementation register, at its canonical
    # repository path. It must be present in every cumulative archive
    # (register section 1.4), and PACK-11 is the round that first places
    # it in the repository rather than passing it alongside.
    "docs/roadmap/EPD2_MASTER_FUTURE_IMPLEMENTATION_REGISTER.md",
)


def find_missing_required_paths(root: Path) -> list[str]:
    """Return the list of required paths (relative, as strings) that are
    missing under `root`."""
    missing: list[str] = []
    for rel_path in REQUIRED_PATHS:
        if not (root / rel_path).exists():
            missing.append(rel_path)
    return missing


def main() -> int:
    missing = find_missing_required_paths(REPO_ROOT)
    if missing:
        print("Missing required paths:")
        for path in missing:
            print(f"  - {path}")
        return 1
    print(f"OK: all {len(REQUIRED_PATHS)} required paths are present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
