"""Detector codes for the INFRA-01 acceptance harness.

Every fail-closed refusal the harness can issue carries exactly one of these
stable machine-readable codes. The mutation suite for the harness proves that
each representative corruption class is caught by *its own* detector — a
shared generic "poison marker" that lets dozens of mutations pass through one
unrelated detector would make the coverage numbers a lie, so the codes are
deliberately fine-grained and the mutation tests assert the exact code.
"""

from __future__ import annotations

# Evidence reconciliation (INFRA01-HI-04 / HI-05)
EVIDENCE_MISSING = "EVIDENCE_MISSING"
EVIDENCE_HASH_MISMATCH = "EVIDENCE_HASH_MISMATCH"
EVIDENCE_TRUNCATED = "EVIDENCE_TRUNCATED"
COMMIT_MISMATCH = "COMMIT_MISMATCH"
ARCHIVE_SHA_MISMATCH = "ARCHIVE_SHA_MISMATCH"
RUN_BINDING_MISMATCH = "RUN_BINDING_MISMATCH"
STALE_EVIDENCE = "STALE_EVIDENCE"
TEST_COUNT_MISMATCH = "TEST_COUNT_MISMATCH"
ZERO_TESTS_EXECUTED = "ZERO_TESTS_EXECUTED"
EXPECTED_OUTPUT_MISSING = "EXPECTED_OUTPUT_MISSING"
MANDATORY_CHECK_MISSING = "MANDATORY_CHECK_MISSING"
MANDATORY_STAGE_MISSING = "MANDATORY_STAGE_MISSING"
CHECK_NOT_EXECUTED = "CHECK_NOT_EXECUTED"
MANIFEST_INTEGRITY_FAILURE = "MANIFEST_INTEGRITY_FAILURE"
INTERNAL_INCONSISTENCY = "INTERNAL_INCONSISTENCY"

# Candidate identity (INFRA01-HI-01)
IDENTITY_INCOMPLETE = "IDENTITY_INCOMPLETE"
VERSION_MISMATCH = "VERSION_MISMATCH"
LOCK_HASH_MISMATCH = "LOCK_HASH_MISMATCH"
DIRTY_TREE = "DIRTY_TREE"

# Byte identity (INFRA01-HI-02)
TREE_MUTATION_AFTER_FREEZE = "TREE_MUTATION_AFTER_FREEZE"
ARCHIVE_BYTE_MISMATCH = "ARCHIVE_BYTE_MISMATCH"
UNDECLARED_ARCHIVE_ENTRY = "UNDECLARED_ARCHIVE_ENTRY"
MISSING_ARCHIVE_ENTRY = "MISSING_ARCHIVE_ENTRY"
DUPLICATE_ARCHIVE_PATH = "DUPLICATE_ARCHIVE_PATH"

# Hygiene (INFRA01-HI-06)
FORBIDDEN_PATH = "FORBIDDEN_PATH"
NESTED_REPOSITORY = "NESTED_REPOSITORY"
NESTED_ARCHIVE = "NESTED_ARCHIVE"
MACHINE_LOCAL_PATH = "MACHINE_LOCAL_PATH"
UNSAFE_ARCHIVE_PATH = "UNSAFE_ARCHIVE_PATH"

# Frozen artifacts (INFRA01-HI-07)
FROZEN_ARTIFACT_MISMATCH = "FROZEN_ARTIFACT_MISMATCH"
FROZEN_ARTIFACT_MISSING = "FROZEN_ARTIFACT_MISSING"

# Secrets (INFRA01-HI-08)
SECRET_DETECTED = "SECRET_DETECTED"
EVIDENCE_SANITATION_FAILURE = "EVIDENCE_SANITATION_FAILURE"

# Governance (INFRA01-HI-03 / entrypoint gate)
COMPETING_REGISTER = "COMPETING_REGISTER"
GOVERNANCE_FILE_MISSING = "GOVERNANCE_FILE_MISSING"
REGISTRY_INTEGRITY_FAILURE = "REGISTRY_INTEGRITY_FAILURE"

# Deployment / readiness foundations (INFRA01-HI-09 / HI-10)
DEPLOYMENT_MANIFEST_INVALID = "DEPLOYMENT_MANIFEST_INVALID"
COMPATIBILITY_NOT_DECLARED = "COMPATIBILITY_NOT_DECLARED"
READINESS_UNKNOWN_FAILS_CLOSED = "READINESS_UNKNOWN_FAILS_CLOSED"
READINESS_DIMENSION_NOT_READY = "READINESS_DIMENSION_NOT_READY"

# Structural non-ownership (INFRA01-HI-11)
DOMAIN_LOGIC_IN_INFRASTRUCTURE = "DOMAIN_LOGIC_IN_INFRASTRUCTURE"

# Governance freshness / current-target reconciliation (INFRA-01 C1, HI-03)
RECONCILIATION_RECORD_MISSING = "RECONCILIATION_RECORD_MISSING"
RECONCILIATION_INTEGRITY_FAILURE = "RECONCILIATION_INTEGRITY_FAILURE"
GOVERNANCE_RECONCILIATION_MISMATCH = "GOVERNANCE_RECONCILIATION_MISMATCH"
STALE_GOVERNANCE_STATE = "STALE_GOVERNANCE_STATE"
GOVERNANCE_TRANSITION_MISSING = "GOVERNANCE_TRANSITION_MISSING"
GOVERNANCE_REGION_MISSING = "GOVERNANCE_REGION_MISSING"
TARGET_AUTHORITY_MISMATCH = "TARGET_AUTHORITY_MISMATCH"

# Exact-delta accounting and temporal provenance (INFRA-01 C2)
CORRECTION_INVENTORY_MISMATCH = "CORRECTION_INVENTORY_MISMATCH"
RECONCILIATION_TIME_INVALID = "RECONCILIATION_TIME_INVALID"
