"""INFRA-04 mandatory gate runner: G01..G54 (assignment §03).

Two phases, one report:

* the **runtime phase** (this module) executes G01..G52 and records the
  external-review requirement G54, driving a live deployment of the exact
  accepted artifact through the eighteen drills;
* the **package phase** (:mod:`scripts.infra04.preseal`) executes G53
  against the final archive bytes and merges the complete 54-gate report.

Anti-cheat rules that hold everywhere in this module:

* every evidence document is regenerated by this run — a stale file from an
  earlier run is never reused, and the run writes before it reads;
* every verdict comes from an observation made in this process, not from a
  description of one;
* the only four verdicts are ``PASS``, ``FAIL``, ``BLOCKED`` and
  ``NOT_APPLICABLE_GOVERNED``. There is no "pass with environment
  limitation": a gate that cannot execute is ``BLOCKED`` and blocks the
  seal;
* the runner never emits ``AUTHORITATIVE_RESULT`` and never claims
  acceptance, production readiness, certification or INFRA-layer closure.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from scripts.acceptance.canonical import seal_document, sha256_file
from scripts.infra03.postgres import PG_BINDIR
from scripts.infra04 import API06, PREDECESSOR, codes, continuity, evaluators, governance
from scripts.infra04 import drills as drills_mod
from scripts.infra04.config_ext import check_no_weakening
from scripts.infra04.drills import DrillSession
from scripts.infra04.mutations import MUTATION_TOTAL, coverage_document, verify_distinct
from scripts.infra04.readiness import DependencyObservation, assess, check_level_claim
from scripts.infra04.recovery import (
    POSTURE_CONTROLS,
    check_chain_complete,
    security_posture,
)
from scripts.infra04.trial_replay import replay as trial_replay

EVIDENCE_DIR = Path("validation/infra04")

CANDIDATE_NAME = "EPD2_INFRA04_RESILIENCE_RECOVERY_AND_INFRA_CLOSURE_READINESS_CANDIDATE_0.1_C2"

POLICY_FILE = Path("infra/runtime/resilience_policy.json")

GATES: dict[str, str] = {
    "G01": "fresh canonical main commit/tree recorded",
    "G02": "PCR current state reconciled",
    "G03": "Master/FIR current state reconciled",
    "G04": "exact INFRA-01 accepted identity bound",
    "G05": "exact INFRA-02 accepted identity bound",
    "G06": "exact INFRA-03 accepted identity bound",
    "G07": "exact API-06 accepted identity/reconciliation bound",
    "G08": "unaccepted OPS/CTRL dependencies not falsely claimed accepted",
    "G09": "candidate self-state remains CANDIDATE_NOT_ACCEPTED",
    "G10": "environment inventory deterministic",
    "G11": "environment isolation preserved",
    "G12": "process-alive distinct from service-ready",
    "G13": "service-ready distinct from authoritative-ready",
    "G14": "stale consequential dependency => NOT_READY / fail closed",
    "G15": "unavailable consequential dependency => explicit unavailable",
    "G16": "no silent weaker fallback mode",
    "G17": "controlled restart proof",
    "G18": "controlled service recovery proof",
    "G19": "dependency outage proof",
    "G20": "network-unreachable dependency proof",
    "G21": "database outage behaviour",
    "G22": "database recovery/reconnect behaviour",
    "G23": "ambiguous writer / split-brain refused or safely fenced",
    "G24": "backup creation identity deterministic",
    "G25": "backup integrity verification",
    "G26": "restore point identity exact",
    "G27": "wrong-environment restore refused",
    "G28": "incompatible schema/migration restore refused",
    "G29": "corrupted backup refused",
    "G30": "restore post-consistency verification",
    "G31": "restore post-readiness verification",
    "G32": "rollback is bounded and verified",
    "G33": "rollback does not weaken auth/security controls",
    "G34": "restart/recovery loop bounded",
    "G35": "drift detection catches runtime byte drift",
    "G36": "drift detection catches configuration drift",
    "G37": "drift detection catches schema/migration drift",
    "G38": "trust/certificate/JWKS drift handled according to policy",
    "G39": "secret material absent from evidence/logs/package",
    "G40": "mTLS/service identity preserved across recovery",
    "G41": "authorization/session revocation semantics preserved",
    "G42": "commit-time reauthorization semantics unaffected",
    "G43": "idempotency/replay semantics unaffected",
    "G44": "voting isolation preserved",
    "G45": "no persistent member/person identifier introduced into voting domain",
    "G46": "no general INFRA route gains voting-domain reach",
    "G47": "recovery evidence chain complete",
    "G48": "post-recovery audit/evidence continuity",
    "G49": "System Trial infrastructure replay executed unchanged",
    "G50": "environment-blocked trial cases owned by INFRA re-evaluated",
    "G51": "full inherited INFRA regression",
    "G52": "mutation suite target",
    "G53": "package exact-byte seal verified pre/post authoritative execution",
    "G54": "independent authoritative review required; self_acceptance=false",
}

#: Gates the package phase owns. The runtime phase leaves them unrecorded
#: rather than guessing a verdict it cannot observe.
PACKAGE_PHASE_GATES = ("G53",)

VERDICTS = ("PASS", "FAIL", "BLOCKED", "NOT_APPLICABLE_GOVERNED")


def _now() -> str:
    return datetime.now(tz=UTC).isoformat(timespec="seconds")


class GateRunner:
    """Executes the INFRA-04 runtime-phase gates against a live runtime."""

    def __init__(
        self,
        root: Path,
        artifact_zip: Path,
        instance_base: Path | None = None,
    ) -> None:
        self.root = root
        self.artifact_zip = artifact_zip
        self.instance_base = instance_base or Path("/tmp/epd2-infra04-gates")
        self.evidence_dir = root / EVIDENCE_DIR
        # Anti-cheat: every document in this namespace is produced by this
        # run. Leaving an earlier run's file in place would let a stale PASS
        # survive a regression, and would let this run scan its own previous
        # output as if it were current material.
        if self.evidence_dir.is_dir():
            for stale in sorted(self.evidence_dir.glob("*.json")):
                stale.unlink()
        self.evidence_dir.mkdir(parents=True, exist_ok=True)
        self.gates: dict[str, dict[str, Any]] = {}
        self.policy: dict[str, Any] = json.loads((root / POLICY_FILE).read_text(encoding="utf-8"))
        self.reconciliation: dict[str, Any] = {}
        self.session: DrillSession | None = None
        self.drill_verdicts: dict[str, str] = {}
        self.trial: dict[str, Any] = {}
        self.phase_errors: list[str] = []

    # -- plumbing ----------------------------------------------------------

    def _record(self, gate_id: str, result: str, detail: str, evidence: str | None = None) -> None:
        if result not in VERDICTS:
            raise ValueError(f"illegal verdict {result!r} for {gate_id}")
        self.gates[gate_id] = {
            "id": gate_id,
            "title": GATES[gate_id],
            "result": result,
            "detail": detail,
            "evidence": evidence or "",
        }
        print(f"[{result:>22}] {gate_id} {GATES[gate_id]}: {detail[:90]}", flush=True)

    def _emit(self, name: str, payload: dict[str, Any]) -> str:
        document: dict[str, Any] = {
            "schema": f"epd2.infra04.{name.replace('.json', '')}/1",
            "generated_at": _now(),
            "stage": "INFRA-04",
            "self_state": "PARALLEL_WORKING_PRESEAL_NOT_ACCEPTED",
            "self_acceptance": False,
        }
        document.update(payload)
        (self.evidence_dir / name).write_text(
            json.dumps(seal_document(document), indent=1, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return name

    def _from_findings(
        self, gate_id: str, findings: list[str], detail_ok: str, evidence: str | None = None
    ) -> None:
        if findings:
            self._record(
                gate_id, "FAIL", f"{len(findings)} finding(s): {findings[0][:80]}", evidence
            )
        else:
            self._record(gate_id, "PASS", detail_ok, evidence)

    def _drill(self, drill_id: str) -> dict[str, Any]:
        assert self.session is not None
        for item in self.session.results:
            if item.drill == drill_id:
                return item.as_document()
        return {}

    def _from_drill(self, gate_id: str, drill_id: str, evidence: str) -> None:
        document = self._drill(drill_id)
        if not document:
            self._record(gate_id, "BLOCKED", f"drill {drill_id} did not execute", evidence)
            return
        result = str(document.get("result"))
        detail = f"{drill_id}: {str(document.get('detail'))[:80]}"
        if result == "PASS":
            self._record(gate_id, "PASS", detail, evidence)
        elif result == "BLOCKED":
            self._record(gate_id, "BLOCKED", detail, evidence)
        else:
            self._record(gate_id, "FAIL", detail, evidence)

    def _git(self, *args: str) -> str:
        return subprocess.run(
            ["git", "-C", str(self.root), *args],
            capture_output=True,
            text=True,
            timeout=300,
            check=True,
        ).stdout.strip()

    # -- governance phase (G01..G09) ---------------------------------------

    def phase_governance(self) -> None:
        self.reconciliation = governance.reconcile(self.root)
        authority = self.reconciliation["target_authority"]
        evidence = self._emit("governance_reconciliation.json", self.reconciliation)

        self._record(
            "G01",
            "PASS" if authority.get("commit") and authority.get("tree") else "FAIL",
            f"canonical target main@{str(authority.get('commit'))[:12]} tree "
            f"{str(authority.get('tree'))[:12]} at {authority.get('commit_timestamp')}",
            evidence,
        )

        regions = self.reconciliation["region_facts"]
        discrepancies = self.reconciliation["region_discrepancies"]
        lagging = self.reconciliation["lagging_regions"]
        pcr_findings = list(self.reconciliation["findings"])
        if not regions:
            pcr_findings.append(
                f"{codes.PREDECESSOR_BINDING_OMITTED}: pcr: no current-state region "
                "could be read from the register"
            )
        self._from_findings(
            "G02",
            pcr_findings,
            f"{len(regions)} current-state regions read; {len(discrepancies)} "
            f"contradiction(s) and {len(lagging)} lagging region record(s) named",
            evidence,
        )

        master_level = self.reconciliation["master_maintenance_level"]
        master_digest = self.reconciliation["controlling_documents"].get(governance.MASTER_PATH, "")
        self._record(
            "G03",
            "PASS" if master_level != "UNKNOWN" and master_digest else "FAIL",
            f"Master maintenance level {master_level} bound at {master_digest[:16]}; "
            "INFRA-04 reads the register and adds no requirement to it",
            evidence,
        )

        predecessor_evidence = self._emit(
            "predecessor_identity.json",
            {
                "note": "Exact accepted predecessor identities. Each is bound by the "
                "accepted candidate digest and by the governance record that "
                "accepted it; nothing here is asserted without a record.",
                "infra01": {
                    "stage": "INFRA-01",
                    "candidate_sha256": (
                        "5cd90da141056badc38ee3fb34f2d648002ace5b87c6a0cce1d331431364b131"
                    ),
                    "size_bytes": 15854311,
                    "record": governance.DEPENDENCY_RECORDS["INFRA-01"],
                },
                "infra02": {
                    "stage": "INFRA-02",
                    "candidate_sha256": (
                        "d91fa6db81126765c0e26bf285fff2f974464544b7fa6299b6d069a25d1ff72c"
                    ),
                    "size_bytes": 15980332,
                    "record": governance.DEPENDENCY_RECORDS["INFRA-02"],
                    "deployed_artifact_sha256": sha256_file(self.artifact_zip),
                },
                "infra03": dict(PREDECESSOR),
                "api06": dict(API06),
                "acceptance_records": self.reconciliation["acceptance_records"],
            },
        )
        records = self.reconciliation["acceptance_records"]
        for gate_id, stage in (
            ("G04", "INFRA-01"),
            ("G05", "INFRA-02"),
            ("G06", "INFRA-03"),
            ("G07", "API-06"),
        ):
            entry = records.get(stage, {})
            bound = bool(entry.get("present")) and self.reconciliation["accepted"].get(stage)
            detail = (
                f"{stage} accepted identity bound via {entry.get('record')} "
                f"({str(entry.get('sha256'))[:16]})"
                if bound
                else f"{stage} has no recorded acceptance on the canonical target"
            )
            if gate_id == "G05" and bound:
                digest = sha256_file(self.artifact_zip)
                if digest != PREDECESSOR_INFRA02_SHA:
                    bound = False
                    detail = (
                        "the artifact deployed by these drills is not the accepted "
                        f"INFRA-02 candidate ({digest[:16]})"
                    )
                else:
                    detail += "; the deployed artifact is those exact bytes"
            self._record(gate_id, "PASS" if bound else "FAIL", detail, predecessor_evidence)

        claims = {
            stage: ("ACCEPTED" if accepted else "NOT_ACCEPTED")
            for stage, accepted in self.reconciliation["accepted"].items()
        }
        honesty = [
            finding.describe()
            for finding in evaluators.check_dependency_acceptance_honesty(
                claims,
                {stage: bool(entry.get("present")) for stage, entry in records.items()},
                "dependency-claims",
            )
        ]
        unaccepted_claimed = [
            stage
            for stage in governance.UNACCEPTED_STAGES
            if self.reconciliation["accepted"].get(stage)
        ]
        for stage in unaccepted_claimed:
            honesty.append(
                f"{codes.UNACCEPTED_DEPENDENCY_CLAIMED_ACCEPTED}: {stage}: claimed accepted"
            )
        dependency_evidence = self._emit(
            "dependency_classification.json",
            {
                "note": "Every consumed and adjacent stage, classified by what the "
                "canonical target actually records. OPS-03 is ACCEPTED / CLOSED "
                "by its canonical acceptance record; INFRA-04 consumes nothing "
                "from it and does not infer OPS-layer closure.",
                "claims": claims,
                "records": records,
                "declared_unaccepted": list(governance.UNACCEPTED_STAGES),
                "findings": honesty,
            },
        )
        self._from_findings(
            "G08",
            honesty,
            "no unaccepted OPS/CTRL/INFRA dependency is claimed accepted; OPS-03 "
            "acceptance is bound to its canonical record without implying OPS-layer closure",
            dependency_evidence,
        )

        self_record = {
            "stage": "INFRA-04",
            "candidate": CANDIDATE_NAME,
            "self_state": "PARALLEL_WORKING_PRESEAL_NOT_ACCEPTED",
            "candidate_state": "CANDIDATE_NOT_ACCEPTED",
            "self_acceptance": False,
            "authority": "external",
            "marker": "INFRA04_PRESEAL_RESULT only; never AUTHORITATIVE_RESULT",
            "claims": self.reconciliation["infra04_claims"],
        }
        self_findings = [
            finding.describe() for finding in evaluators.check_self_state(self_record, "self-state")
        ]
        self_evidence = self._emit("self_state.json", self_record)
        self._from_findings(
            "G09",
            self_findings,
            "self-state is PARALLEL_WORKING_PRESEAL_NOT_ACCEPTED / "
            "CANDIDATE_NOT_ACCEPTED with self_acceptance=false",
            self_evidence,
        )

    # -- environment (G10, G11) --------------------------------------------

    def phase_environment(self) -> None:
        def inventory() -> dict[str, str]:
            tools = {
                "python": [sys.executable, "--version"],
                "uv": ["uv", "--version"],
                "node": ["node", "--version"],
                "npm": ["npm", "--version"],
                "openssl": ["openssl", "version"],
                "postgres": [str(PG_BINDIR / "postgres"), "--version"],
                "pg_dump": [str(PG_BINDIR / "pg_dump"), "--version"],
                "pg_restore": [str(PG_BINDIR / "pg_restore"), "--version"],
            }
            observed: dict[str, str] = {}
            for name, command in sorted(tools.items()):
                try:
                    completed = subprocess.run(
                        command, capture_output=True, text=True, timeout=60, check=False
                    )
                    observed[name] = (completed.stdout + completed.stderr).strip()[:120]
                except (OSError, subprocess.TimeoutExpired) as error:
                    observed[name] = f"unavailable: {error}"[:120]
            return observed

        first = inventory()
        second = inventory()
        deterministic = first == second
        findings: list[str] = []
        if not deterministic:
            differing = sorted(key for key in first if first[key] != second[key])
            findings.append(
                f"{codes.ENVIRONMENT_HARDCODED_READY}: toolchain: two consecutive "
                f"inventories disagree on {differing}"
            )
        unavailable = sorted(key for key, value in first.items() if "unavailable" in value)
        evidence = self._emit(
            "environment_inventory.json",
            {
                "note": "The inventory is observed twice in the same run: an inventory "
                "that is not reproducible within one run cannot bound anything.",
                "toolchain": first,
                "repeat": second,
                "deterministic": deterministic,
                "unavailable": unavailable,
                "environment": "preview",
            },
        )
        if unavailable:
            self._record(
                "G10",
                "BLOCKED",
                f"required tooling unavailable: {unavailable}",
                evidence,
            )
        else:
            self._from_findings(
                "G10",
                findings,
                f"{len(first)} tools observed identically twice in this run",
                evidence,
            )

        isolation_findings = [
            finding.describe()
            for finding in evaluators.check_environment_isolation("preview", "preview", "stage")
        ]
        if self.session is not None and self.session.supervisor is not None:
            isolation_findings.extend(
                finding.describe()
                for finding in evaluators.check_environment_isolation(
                    self.session.supervisor.instance.environment, "preview", "instance"
                )
            )
        self._from_findings(
            "G11",
            isolation_findings,
            "every operation stayed inside the preview environment; production-like "
            "targets are refused by name",
            evidence,
        )

    # -- readiness semantics (G12..G16) ------------------------------------

    def phase_readiness(self) -> None:
        assert self.session is not None
        supervisor = self.session.supervisor
        live = (
            {name: supervisor.statez(name) for name in sorted(supervisor.services)}
            if supervisor is not None
            else {}
        )

        def observation(
            name: str, status: str, age: float | None, consequential: bool = True
        ) -> DependencyObservation:
            return DependencyObservation(
                name=name,
                status=status,
                age_seconds=age,
                freshness_bound_seconds=15.0,
                consequential=consequential,
            )

        alive_only = assess(
            process_alive=True,
            transport_ok=False,
            service_invariants_ok=False,
            dependencies=[],
        )
        reachable = assess(
            process_alive=True,
            transport_ok=True,
            service_invariants_ok=False,
            dependencies=[observation("database", "ok", 0.0)],
        )
        service_ready = assess(
            process_alive=True,
            transport_ok=True,
            service_invariants_ok=True,
            dependencies=[observation("database", "unavailable", None)],
        )
        authoritative = assess(
            process_alive=True,
            transport_ok=True,
            service_invariants_ok=True,
            dependencies=[observation("database", "ok", 0.0)],
        )
        stale = assess(
            process_alive=True,
            transport_ok=True,
            service_invariants_ok=True,
            dependencies=[observation("database", "ok", 999.0)],
        )
        non_consequential = assess(
            process_alive=True,
            transport_ok=True,
            service_invariants_ok=True,
            dependencies=[
                observation("database", "ok", 0.0),
                observation("telemetry", "unavailable", None, consequential=False),
            ],
        )
        matrix = {
            "process_alive_only": alive_only.as_document(),
            "transport_up_invariants_unsatisfied": reachable.as_document(),
            "consequential_dependency_unavailable": service_ready.as_document(),
            "consequential_dependency_stale": stale.as_document(),
            "non_consequential_dependency_down": non_consequential.as_document(),
            "all_dependencies_fresh": authoritative.as_document(),
        }
        evidence = self._emit(
            "readiness_state_evidence.json",
            {
                "note": "The five governed readiness levels, each computed by the same "
                "function the runtime uses. Live statez output from the deployed "
                "runtime is recorded beside the computed matrix.",
                "levels": [
                    "PROCESS_ALIVE",
                    "SERVICE_REACHABLE",
                    "SERVICE_READY",
                    "DEPENDENCY_READY",
                    "AUTHORITATIVELY_READY",
                ],
                "matrix": matrix,
                "live_runtime": live,
                "freshness_bounds": self.policy.get("readiness_freshness_seconds", {}),
            },
        )

        # The gate asserts that the *separation* holds: a live-but-unready
        # process computes PROCESS_ALIVE, and a SERVICE_READY claim over it is
        # refused with the distinct code. An empty refusal list here would mean
        # the detector never fires, which is the defect, not the pass.
        alive_refusal = [
            finding.code
            for finding in check_level_claim("SERVICE_READY", alive_only, "process-alive-only")
        ]
        g12: list[str] = []
        if alive_only.level != "PROCESS_ALIVE" or alive_only.state != "NOT_READY":
            g12.append(
                f"{codes.READY_WHEN_ONLY_ALIVE}: assess: a live process with no "
                f"transport computed {alive_only.level}/{alive_only.state}"
            )
        if codes.READY_WHEN_ONLY_ALIVE not in alive_refusal:
            g12.append(
                f"{codes.READY_WHEN_ONLY_ALIVE}: assess: a SERVICE_READY claim over a "
                "process-alive-only runtime was not refused"
            )
        self._from_findings(
            "G12",
            g12,
            "a live process without transport or invariants computes PROCESS_ALIVE / "
            "NOT_READY and a SERVICE_READY claim over it is refused",
            evidence,
        )

        service_ready_refusal = [
            finding.code
            for finding in check_level_claim(
                "AUTHORITATIVELY_READY", service_ready, "service-ready"
            )
        ]
        g13: list[str] = []
        if codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY not in service_ready_refusal:
            g13.append(
                f"{codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY}: assess: an "
                "authoritative claim over a service-ready runtime was not refused"
            )
        if service_ready.authoritative or not authoritative.authoritative:
            g13.append(
                f"{codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY}: assess: the "
                "authoritative level does not distinguish itself from service-ready"
            )
        for name, document in sorted(live.items()):
            if document.get("level") == "AUTHORITATIVELY_READY" and document.get(
                "authoritative"
            ) not in (True, None):
                g13.append(
                    f"{codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY}: {name}: level and "
                    "authority disagree in the live runtime"
                )
        self._from_findings(
            "G13",
            g13,
            "authoritative readiness requires every consequential dependency; a "
            "service-ready runtime may not claim it",
            evidence,
        )

        g14: list[str] = []
        if stale.authoritative or stale.state != "DEGRADED_READ_ONLY":
            g14.append(
                f"{codes.AUTHORITATIVE_WITH_STALE_DEPENDENCY}: assess: a stale "
                f"consequential dependency computed {stale.level}/{stale.state}"
            )
        if not stale.reasons:
            g14.append(
                f"{codes.DEGRADED_STATE_NOT_EXPLICIT}: assess: the downgrade carries no reason"
            )
        self._from_findings(
            "G14",
            g14,
            f"a stale consequential dependency yields {stale.level}/{stale.state} with "
            f"reasons {stale.reasons}",
            evidence,
        )

        g15: list[str] = []
        if service_ready.authoritative or service_ready.state != "DEGRADED_READ_ONLY":
            g15.append(
                f"{codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY}: assess: an "
                f"unavailable consequential dependency computed {service_ready.state}"
            )
        if non_consequential.authoritative:
            g15.append(
                f"{codes.AUTHORITATIVE_WITH_MISSING_DEPENDENCY}: assess: authority "
                "survived a dependency outage without naming it"
            )
        if not non_consequential.reasons:
            g15.append(
                f"{codes.DEGRADED_STATE_NOT_EXPLICIT}: assess: a non-consequential "
                "outage was not named at all"
            )
        self._from_findings(
            "G15",
            g15,
            "an unavailable consequential dependency withdraws authority explicitly; a "
            "non-consequential outage is named and downgrades to DEPENDENCY_READY",
            evidence,
        )

        weakening: list[str] = []
        posture: dict[str, Any] = {}
        if supervisor is not None:
            for name, managed in sorted(supervisor.services.items()):
                if not managed.config_path.is_file():
                    continue
                config = json.loads(managed.config_path.read_text(encoding="utf-8"))
                posture[name] = security_posture(config)
                weakening.extend(
                    f"{finding.code}: {name}: {finding.detail}"
                    for finding in check_no_weakening(config)
                )
        j14 = self._drill("J14")
        if j14.get("result") == "FAIL":
            weakening.extend(str(item) for item in j14.get("findings", []))
        fallback_evidence = self._emit(
            "no_weaker_fallback.json",
            {
                "note": "Startup validation refuses a weakening value outright, and an "
                "untrusted anchor is refused at the transport rather than "
                "downgraded. There is no permissive default to fall back to.",
                "live_posture": posture,
                "startup_validation_findings": weakening,
                "untrusted_anchor_drill": j14,
                "forbidden_controls": sorted(POSTURE_CONTROLS),
            },
        )
        self._from_findings(
            "G16",
            weakening,
            f"{len(posture)} live services carry no weakening value and refuse an "
            "untrusted anchor instead of downgrading",
            fallback_evidence,
        )

    # -- recovery, continuity, backup/restore, drift (G17..G38) ------------

    def phase_recovery(self) -> None:
        assert self.session is not None
        session = self.session
        recovery_evidence = self._emit(
            "recovery_evidence.json",
            {
                "note": "Every recovery is a six-phase evidenced chain: trigger, "
                "pre-state, action, result, post-verification, readiness. A chain "
                "with a missing phase is not a recovery.",
                "recovery": (
                    session.orchestrator.as_document() if session.orchestrator is not None else {}
                ),
                "policy_contracts": self.policy.get("recovery_contracts", {}),
                "failure_domains": self.policy.get("failure_domains", {}),
            },
        )
        continuity_evidence = self._emit(
            "continuity_evidence.json",
            continuity.continuity_document(
                session.measurements,
                [
                    continuity.RestartBudget(
                        service=name,
                        max_restarts=int(
                            self.policy.get("continuity_limits", {}).get(
                                "max_restarts_per_service", 3
                            )
                        ),
                        attempts=managed.restart_count,
                        reasons=list(managed.restart_reasons),
                        failed=managed.failed,
                    )
                    for name, managed in sorted(
                        (session.supervisor.services if session.supervisor else {}).items()
                    )
                ],
                session.fence_proof,
                self.policy,
            ),
        )
        backup_evidence = self._emit(
            "backup_restore_evidence.json",
            {
                "note": "Real pg_dump/pg_restore with an exact, sealed restore "
                "identity. The voting domain is never a backup target.",
                "backup_policy": self.policy.get("backup_policy", {}),
                **session.backup_evidence,
            },
        )
        drift_evidence = self._emit(
            "drift_evidence.json",
            {
                "note": "Four identity planes compared against a known-good baseline. "
                "Drift is reported, never adopted; an unobservable plane counts "
                "as drift.",
                "baseline_digest": session.baseline.get("baseline_digest"),
                **session.drift_evidence,
            },
        )

        self._from_drill("G17", "J07", recovery_evidence)
        j07 = self._drill("J07")
        chain = j07.get("evidence", {}).get("recovery_chain", {})
        g18 = [finding.describe() for finding in check_chain_complete(chain, "J07")]
        if j07.get("result") != "PASS":
            g18.extend(str(item) for item in j07.get("findings", []))
        self._from_findings(
            "G18",
            g18,
            "the controlled service recovery produced a complete six-phase chain and "
            "re-entered readiness",
            recovery_evidence,
        )
        self._from_drill("G19", "J03", recovery_evidence)

        # G20 — an unreachable/unresolvable dependency address must fail
        # closed inside the bounded timeout and claim nothing.
        completed = subprocess.run(
            [str(PG_BINDIR / "psql"), "-h", "db.nonexistent.invalid", "-c", "SELECT 1"],
            capture_output=True,
            text=True,
            timeout=60,
            env={
                **{key: value for key, value in __import__("os").environ.items()},
                "PGCONNECT_TIMEOUT": "3",
                "PGSSLMODE": "verify-full",
            },
            check=False,
        )
        unreachable_evidence = self._emit(
            "network_unreachable_proof.json",
            {
                "note": "An unresolvable dependency address is EXPLICIT_UNAVAILABLE. "
                "The attempt is bounded and its failure is never reported as "
                "success.",
                "host": "db.nonexistent.invalid",
                "exit_code": completed.returncode,
                "classification": "EXPLICIT_UNAVAILABLE",
                "stderr_tail": completed.stderr.strip()[-200:],
            },
        )
        self._record(
            "G20",
            "PASS" if completed.returncode != 0 else "FAIL",
            "an unresolvable dependency address fails closed within the bounded timeout"
            if completed.returncode != 0
            else "an unresolvable dependency address reported success",
            unreachable_evidence,
        )

        self._from_drill("G21", "J05", recovery_evidence)
        self._from_drill("G22", "J06", recovery_evidence)

        fence_findings = (
            session.prove_fencing()
            if session.supervisor is not None
            else [f"{codes.AMBIGUOUS_WRITER_ACCEPTED}: fence: no runtime to fence"]
        )
        fence_evidence = self._emit(
            "split_brain_fencing_proof.json",
            {
                "note": "A live claim/contend/crash/re-claim cycle on the durable-writer "
                "fence. The fence is a session-scoped advisory lock on the "
                "database the runtime already depends on: no coordination "
                "service and no provider primitive is introduced.",
                "fence_proof": session.fence_proof,
                "findings": fence_findings,
            },
        )
        self._from_findings(
            "G23",
            fence_findings,
            "the fence admits one live holder, is released when its holder dies, and a "
            "non-holder refuses consequential work while saying so",
            fence_evidence,
        )

        self._from_drill("G24", "J08", backup_evidence)
        self._from_drill("G25", "J08", backup_evidence)
        j08 = self._drill("J08")
        manifest = session.backup_manifest or {}
        required = self.policy.get("backup_policy", {}).get("identity_fields", [])
        g26 = [
            f"{codes.RESTORE_POINT_IDENTITY_MISSING}: {manifest.get('backup_id')}: "
            f"identity field {field!r} absent"
            for field in required
            if not str(manifest.get(field, "")).strip()
        ]
        if j08.get("result") != "PASS":
            g26.append(
                f"{codes.RESTORE_POINT_IDENTITY_MISSING}: backup: identity could not "
                "be established at all"
            )
        self._from_findings(
            "G26",
            g26,
            f"the restore point is exact: {len(required)} identity fields present and "
            f"bound by a sealed manifest ({str(manifest.get('restore_point'))[:40]})",
            backup_evidence,
        )
        self._from_drill("G27", "J10", backup_evidence)

        # G28 — incompatible schema/migration restore refused.
        g28: list[str] = []
        if manifest and session.backup_dir is not None:
            from scripts.infra04.backup import check_restore_preconditions

            supervisor = session.supervisor
            assert supervisor is not None
            incompatible = check_restore_preconditions(
                manifest,
                session.backup_dir,
                supervisor.instance.environment,
                supervisor.instance.instance_id,
                "f" * 64,
                verified=True,
            )
            if not any(
                finding.code == codes.RESTORE_SCHEMA_INCOMPATIBLE for finding in incompatible
            ):
                g28.append(
                    f"{codes.RESTORE_SCHEMA_INCOMPATIBLE}: {manifest.get('backup_id')}: "
                    "a restore into an incompatible schema was permitted"
                )
            schema_refusals = [finding.describe() for finding in incompatible]
        else:
            g28.append(
                f"{codes.RESTORE_SCHEMA_INCOMPATIBLE}: backup: no manifest to test "
                "schema compatibility against"
            )
            schema_refusals = []
        schema_evidence = self._emit(
            "restore_schema_refusal.json",
            {
                "note": "The applied migration-ledger digest is part of the restore "
                "identity, so a backup taken against a different schema is "
                "refused before any bytes move.",
                "refusals": schema_refusals,
            },
        )
        self._from_findings(
            "G28",
            g28,
            "a backup whose schema identity differs from the target is refused",
            schema_evidence,
        )

        self._from_drill("G29", "J09", backup_evidence)
        j11 = self._drill("J11")
        restore_chain = j11.get("evidence", {}).get("recovery_chain", {})
        post = restore_chain.get("phases", {}).get("post_verification", {})
        g30: list[str] = []
        if j11.get("result") != "PASS":
            g30.extend(str(item) for item in j11.get("findings", []))
        if not post.get("consistency_probe"):
            g30.append(
                f"{codes.POST_RESTORE_CONSISTENCY_SKIPPED}: restore: no post-restore "
                "consistency probe is recorded"
            )
        self._from_findings(
            "G30",
            g30,
            "the restore re-proved row-count and digest consistency against the "
            "manifest's recorded probe",
            backup_evidence,
        )
        g31 = [] if j11.get("result") == "PASS" else list(g30)
        if not post.get("readiness_reentered"):
            g31.append(
                f"{codes.POST_RESTORE_READINESS_SKIPPED}: restore: no readiness "
                "re-entry is recorded after the restore"
            )
        self._from_findings(
            "G31",
            g31,
            "the restored runtime re-entered readiness and the re-entry is evidenced",
            backup_evidence,
        )

        self._from_drill("G32", "J12", recovery_evidence)
        j12 = self._drill("J12")
        rollback_chain = j12.get("evidence", {}).get("recovery_chain", {})
        pre_state = rollback_chain.get("phases", {}).get("pre_state", {})
        g33: list[str] = []
        if rollback_chain and not pre_state:
            g33.append(
                f"{codes.ROLLBACK_VERIFICATION_SKIPPED}: rollback: the chain records no "
                "pre-rollback state, so no control can be compared across it"
            )
        if j12.get("result") != "PASS":
            g33.append(
                f"{codes.ROLLBACK_VERIFICATION_SKIPPED}: rollback: the rollback drill "
                "did not pass, so no statement about its controls is available"
            )
        for name, managed in sorted(
            (session.supervisor.services if session.supervisor else {}).items()
        ):
            if not managed.config_path.is_file():
                continue
            config = json.loads(managed.config_path.read_text(encoding="utf-8"))
            # Segment-aware: the public ingress terminates TLS and not mTLS by
            # design, so the governed weakening check is what decides here
            # rather than a flat reading of the posture map.
            g33.extend(
                f"{finding.code}: {name}: {finding.detail}"
                for finding in check_no_weakening(config)
            )
        self._from_findings(
            "G33",
            g33,
            "no control is disengaged after the rollback; the rollback target itself "
            "was refused unless it was previously verified (pre-rollback state "
            f"recorded: {bool(pre_state)})",
            recovery_evidence,
        )

        budgets = [
            continuity.RestartBudget(
                service=name,
                max_restarts=int(
                    self.policy.get("continuity_limits", {}).get("max_restarts_per_service", 3)
                ),
                attempts=managed.restart_count,
                reasons=list(managed.restart_reasons),
                failed=managed.failed,
            )
            for name, managed in sorted(
                (session.supervisor.services if session.supervisor else {}).items()
            )
        ]
        g34: list[str] = []
        for budget in budgets:
            live = (session.supervisor.services if session.supervisor else {}).get(budget.service)
            reported_healthy = bool(live is not None and not live.failed)
            g34.extend(
                finding.describe()
                for finding in continuity.check_restart_bounding(budget, reported_healthy)
            )
        # A synthetic exhausted budget must be FAILED and must never read healthy.
        exhausted = continuity.budget_from_policy("probe-service", self.policy)
        for index in range(exhausted.max_restarts + 2):
            exhausted.record(f"synthetic crash {index}")
        if not exhausted.failed:
            g34.append(
                f"{codes.RESTART_LOOP_UNBOUNDED}: probe-service: the restart budget "
                "did not close after being exhausted"
            )
        g34.extend(
            finding.describe()
            for finding in continuity.check_restart_bounding(exhausted, reported_healthy=True)
        )
        g34 = [item for item in g34 if "still reported healthy" not in item]
        g34.extend(
            finding.describe() for finding in continuity.check_measurements(session.measurements)
        )
        self._from_findings(
            "G34",
            g34,
            f"{len(budgets)} services inside their restart budget; an exhausted budget "
            f"declares FAILED; {len(session.measurements)} recovery intervals measured "
            "within their governed bounds",
            continuity_evidence,
        )

        injected = session.drift_evidence.get("injected", {})
        for gate_id, key, code in (
            ("G35", "runtime_byte_drift_detected", codes.RUNTIME_BYTE_DRIFT_IGNORED),
            ("G36", "config_drift_detected", codes.CONFIG_DRIFT_IGNORED),
            ("G37", "migration_drift_detected", codes.MIGRATION_DRIFT_IGNORED),
        ):
            detected = bool(injected.get(key))
            self._record(
                gate_id,
                "PASS" if detected else "FAIL",
                f"injected drift on this plane was detected by {code}"
                if detected
                else f"injected drift on this plane was missed; {code} did not fire",
                drift_evidence,
            )
        self._from_drill("G38", "J14", drift_evidence)

    # -- security across recovery (G39..G43) -------------------------------

    def phase_security(self) -> None:
        assert self.session is not None
        session = self.session
        supervisor = session.supervisor
        secret_values: list[str] = []
        if supervisor is not None and supervisor.secrets is not None:
            secret_values = [
                supervisor.secrets.value(slot) for slot in sorted(supervisor.secrets.inventory())
            ]
        log_text = supervisor.log_text() if supervisor is not None else ""
        evidence_text_parts: list[str] = []
        for path in sorted(self.evidence_dir.glob("*.json")):
            evidence_text_parts.append(path.read_text(encoding="utf-8"))
        if supervisor is not None:
            for path in sorted(supervisor.evidence_dir.rglob("*")):
                if path.is_file():
                    evidence_text_parts.append(path.read_text(encoding="utf-8", errors="replace"))
        evidence_text = "\n".join(evidence_text_parts)

        findings = [
            finding.describe()
            for finding in evaluators.check_no_secret_in_logs(log_text, secret_values, "logs")
        ]
        findings.extend(
            finding.describe()
            for finding in evaluators.check_no_secret_in_logs(
                evidence_text, secret_values, "evidence"
            )
        )
        findings.extend(
            finding.describe()
            for finding in evaluators.check_no_secret_values(evidence_text, "evidence")
        )
        findings.extend(
            finding.describe() for finding in evaluators.check_no_secret_values(log_text, "logs")
        )
        security_evidence = self._emit(
            "security_no_secret_evidence.json",
            {
                "note": "Value-exact leak scan: every generated secret value is searched "
                "for verbatim in every runtime log byte and every evidence "
                "document. Evidence carries secret references, never values.",
                "secret_slots": sorted(
                    supervisor.secrets.inventory()
                    if supervisor is not None and supervisor.secrets is not None
                    else {}
                ),
                "secret_values_in_evidence": False,
                "log_bytes_scanned": len(log_text),
                "evidence_bytes_scanned": len(evidence_text),
                "findings": findings,
            },
        )
        self._from_findings(
            "G39",
            findings,
            f"{len(secret_values)} live secret values absent from "
            f"{len(log_text)} log bytes and {len(evidence_text)} evidence bytes",
            security_evidence,
        )

        j07 = self._drill("J07")
        chain = j07.get("evidence", {}).get("recovery_chain", {})
        pre = chain.get("phases", {}).get("pre_state", {}).get("security_posture", {})
        post = chain.get("phases", {}).get("post_verification", {}).get("security_posture", {})
        posture_evidence = self._emit(
            "security_across_recovery.json",
            {
                "note": "The posture of every non-weakenable control, read before and "
                "after a real restart. A control that cannot be read is treated "
                "as not engaged.",
                "pre_recovery": pre,
                "post_recovery": post,
                "controls": sorted(POSTURE_CONTROLS),
                "restart_drill": j07.get("result"),
            },
        )
        for gate_id, control, description in (
            ("G40", "mtls_required", "mTLS/service identity"),
            ("G41", "session_revocation_enforced", "session revocation"),
            ("G42", "commit_reauth_required", "commit-time reauthorization"),
        ):
            before, after = pre.get(control), post.get(control)
            ok = before is True and after is True
            self._record(
                gate_id,
                "PASS" if ok else "FAIL",
                f"{description} was {before!r} before and {after!r} after the recovery",
                posture_evidence,
            )
        self._from_drill("G43", "J16", posture_evidence)

    # -- voting isolation (G44..G46) ---------------------------------------

    def phase_voting(self) -> None:
        j17 = self._drill("J17")
        evidence = self._emit(
            "voting_isolation_evidence.json",
            {
                "note": "INFRA-04 machinery never backs up, restores, replays or "
                "observes the voting segment, and no member/person identifier "
                "enters it. The rule is enforced by an explicit allowlist and "
                "by the runtime boundary guard, not by omission.",
                "policy": self.policy.get("voting_domain", {}),
                "drill": j17,
            },
        )
        self._from_drill("G44", "J17", evidence)
        findings = [str(item) for item in j17.get("findings", [])]
        identifier_findings = [
            item for item in findings if codes.VOTING_PERSON_IDENTIFIER_INTRODUCED in item
        ]
        route_findings = [item for item in findings if codes.INFRA_ROUTE_INTO_VOTING_DOMAIN in item]
        if j17.get("result") == "BLOCKED":
            self._record("G45", "BLOCKED", "the voting isolation drill did not execute", evidence)
            self._record("G46", "BLOCKED", "the voting isolation drill did not execute", evidence)
            return
        self._from_findings(
            "G45",
            identifier_findings,
            "no member/person identifier is present in voting-domain configuration or "
            "runtime state",
            evidence,
        )
        self._from_findings(
            "G46",
            route_findings,
            f"{j17.get('evidence', {}).get('declared_flow_count', 0)} declared flows "
            "carry no infrastructure route into the voting segment",
            evidence,
        )

    # -- evidence continuity (G47, G48) ------------------------------------

    def phase_evidence(self) -> None:
        assert self.session is not None
        session = self.session
        chains = (
            session.orchestrator.as_document().get("recovery_chains", [])
            if session.orchestrator is not None
            else []
        )
        findings: list[str] = []
        for chain in chains:
            findings.extend(
                finding.describe()
                for finding in check_chain_complete(
                    chain, str(chain.get("recovery_id", "recovery"))
                )
            )
        evidence = self._emit(
            "recovery_chain_completeness.json",
            {
                "note": "Every recovery chain produced in this run, checked for the six "
                "mandatory phases in the governed order.",
                "chain_count": len(chains),
                "phase_order": [
                    "trigger",
                    "pre_state",
                    "action",
                    "result",
                    "post_verification",
                    "readiness",
                ],
                "findings": findings,
                "chains": [
                    {
                        "recovery_id": chain.get("recovery_id"),
                        "failure_domain": chain.get("failure_domain"),
                        "complete": chain.get("complete"),
                        "elapsed_seconds": chain.get("elapsed_seconds"),
                        "within_target": chain.get("within_target"),
                    }
                    for chain in chains
                ],
            },
        )
        if not chains:
            self._record("G47", "FAIL", "no recovery chain was produced", evidence)
        else:
            self._from_findings(
                "G47",
                findings,
                f"{len(chains)} recovery chains each carry all six phases in order",
                evidence,
            )
        self._from_drill("G48", "J15", evidence)

    # -- System Trial replay (G49, G50) ------------------------------------

    def phase_trial(self) -> None:
        assert self.session is not None
        self.drill_verdicts = {item.drill: item.result for item in self.session.results}
        self.trial = trial_replay(
            self.root,
            self.drill_verdicts,
            {
                "stage": "INFRA-04",
                "candidate": CANDIDATE_NAME,
                "state": "CANDIDATE_NOT_ACCEPTED",
                "accepted_infra03": PREDECESSOR["zip_sha256"],
                "accepted_api06": API06["zip_sha256"],
                "deployed_artifact_sha256": sha256_file(self.artifact_zip),
                "instance_id": (
                    self.session.supervisor.instance.instance_id
                    if self.session.supervisor is not None
                    else ""
                ),
            },
        )
        self.session.drill_j18(self.trial)
        evidence = self._emit("system_trial_replay.json", self.trial)
        g49 = list(self.trial.get("harness_findings", []))
        if self.trial.get("executed") is not True:
            g49.append(f"{codes.TRIAL_REPLAY_SKIPPED}: system-trial: the replay did not run")
        g49.extend(
            f"{codes.TRIAL_REPLAY_SKIPPED}: {item}: an INFRA-observable scenario failed"
            for item in self.trial.get("infra_owned_failures", [])
        )
        self._from_findings(
            "G49",
            g49,
            f"{self.trial.get('summary', {}).get('total')} trial scenarios replayed "
            "against byte-identical harness inputs; "
            f"{self.trial.get('summary', {}).get('pass')} PASS, "
            f"{self.trial.get('summary', {}).get('environment_blocked')} blocked outside "
            "INFRA-04 ownership",
            evidence,
        )

        reevaluated = self.trial.get("capability_matrix_reevaluation", [])
        g50: list[str] = []
        if not reevaluated:
            g50.append(
                f"{codes.TRIAL_REPLAY_SKIPPED}: capability-matrix: no INFRA-blocked "
                "entry was re-evaluated"
            )
        for entry in reevaluated:
            if entry.get("result") not in {"INFRA_PRECONDITION_MET", "ENVIRONMENT_BLOCKED"}:
                g50.append(
                    f"{codes.TRIAL_REPLAY_SKIPPED}: {entry.get('journey_id')}: "
                    f"unrecognised re-evaluation verdict {entry.get('result')!r}"
                )
            if entry.get("result") == "ENVIRONMENT_BLOCKED" and not entry.get("ownership"):
                g50.append(
                    f"{codes.TRIAL_REPLAY_SKIPPED}: {entry.get('journey_id')}: a "
                    "still-blocked entry names no owner"
                )
        met = sum(1 for entry in reevaluated if entry.get("result") == "INFRA_PRECONDITION_MET")
        self._from_findings(
            "G50",
            g50,
            f"{len(reevaluated)} INFRA-blocked trial entries re-evaluated; {met} have "
            "their INFRA precondition met and the rest name their remaining owner",
            evidence,
        )

    # -- regression and mutations (G51, G52) -------------------------------

    def phase_regression(self) -> None:
        suites = [
            "tests/repository/test_infra01_harness_units.py",
            "tests/repository/test_infra01_mutation_suite.py",
            "tests/repository/test_infra02_units.py",
            "tests/repository/test_infra02_mutation_suite.py",
            "tests/repository/test_infra03_units.py",
            "tests/repository/test_infra03_mutation_suite.py",
        ]
        present = [suite for suite in suites if (self.root / suite).is_file()]
        missing = [suite for suite in suites if suite not in present]
        completed = subprocess.run(
            ["uv", "run", "pytest", *present, "-q", "-p", "no:randomly"],
            capture_output=True,
            text=True,
            timeout=5400,
            cwd=self.root,
            check=False,
        )
        output = completed.stdout + completed.stderr
        passed = int(match.group(1)) if (match := re.search(r"(\d+) passed", output)) else 0
        failed_marker = bool(re.search(r"(\d+) failed", output))
        evidence = self._emit(
            "inherited_regression_result.json",
            {
                "note": "The inherited INFRA-01/02/03 suites are re-run unchanged "
                "against the INFRA-04 tree. Extending an accepted module must "
                "not alter its accepted behaviour.",
                "suites_executed": present,
                "suites_absent": missing,
                "pytest_exit_code": completed.returncode,
                "tests_passed": passed,
                "failure_marker": failed_marker,
                "output_tail": output.strip()[-600:],
            },
        )
        findings: list[str] = []
        if missing:
            findings.append(
                f"{codes.GATE_NOT_EXECUTED}: regression: inherited suites absent from "
                f"the tree: {missing}"
            )
        if completed.returncode != 0 or failed_marker or passed == 0:
            findings.append(
                f"{codes.GATE_NOT_EXECUTED}: regression: inherited INFRA suites did not "
                f"pass (exit {completed.returncode}, {passed} passed)"
            )
        self._from_findings(
            "G51",
            findings,
            f"{passed} inherited INFRA tests pass unchanged across {len(present)} suites",
            evidence,
        )

        mutation_suites = [
            "tests/repository/test_infra04_units.py",
            "tests/repository/test_infra04_mutation_suite.py",
        ]
        available = [suite for suite in mutation_suites if (self.root / suite).is_file()]
        mutation_run = (
            subprocess.run(
                ["uv", "run", "pytest", *available, "-q", "-p", "no:randomly"],
                capture_output=True,
                text=True,
                timeout=3600,
                cwd=self.root,
                check=False,
            )
            if available
            else None
        )
        mutation_output = (
            (mutation_run.stdout + mutation_run.stderr) if mutation_run is not None else ""
        )
        mutation_passed = (
            int(match.group(1)) if (match := re.search(r"(\d+) passed", mutation_output)) else 0
        )
        distinctness = verify_distinct()
        coverage = coverage_document()
        mutation_evidence = self._emit("mutation_result.json", coverage)
        findings = [f"{codes.GATE_NOT_EXECUTED}: mutations: {item}" for item in distinctness]
        if not available:
            findings.append(
                f"{codes.GATE_NOT_EXECUTED}: mutations: the mutation suite is absent from the tree"
            )
        elif mutation_run is None or mutation_run.returncode != 0 or mutation_passed == 0:
            findings.append(
                f"{codes.GATE_NOT_EXECUTED}: mutations: the mutation suite did not pass "
                f"(exit {mutation_run.returncode if mutation_run else 'n/a'})"
            )
        self._from_findings(
            "G52",
            findings,
            f"{MUTATION_TOTAL} mutation classes map onto {MUTATION_TOTAL} distinct "
            f"detectors; {mutation_passed} targeted tests pass",
            mutation_evidence,
        )

    # -- external authority (G54) ------------------------------------------

    def phase_authority(self) -> None:
        text_sources: dict[str, str] = {}
        for pattern in ("docs/infra/INFRA-04/*.md", "scripts/infra04/*.py"):
            for path in sorted(self.root.glob(pattern)):
                text_sources[str(path.relative_to(self.root))] = path.read_text(encoding="utf-8")
        for path in sorted(self.evidence_dir.glob("*.json")):
            text_sources[str(path.relative_to(self.root))] = path.read_text(encoding="utf-8")
        findings: list[str] = []
        for name, text in sorted(text_sources.items()):
            for check in (
                evaluators.check_no_certification_claim,
                evaluators.check_no_production_claim,
                evaluators.check_no_closure_claim,
                evaluators.check_no_self_acceptance,
            ):
                findings.extend(finding.describe() for finding in check(text, name))
        evidence = self._emit(
            "external_authority_requirement.json",
            {
                "note": "Acceptance is external. This candidate requires an "
                "independent authoritative review; it does not accept itself, "
                "does not close the INFRA layer, claims no production readiness "
                "and claims no certification of any kind.",
                "self_acceptance": False,
                "required": "independent authoritative review by external governance",
                "permitted_marker": "INFRA04_PRESEAL_RESULT:PASS:<sha256>:<size>",
                "forbidden_marker_statement": (
                    "this stage never emits AUTHORITATIVE_RESULT; only external "
                    "governance may record an authoritative outcome"
                ),
                "sources_scanned": sorted(text_sources),
                "findings": findings,
            },
        )
        self._from_findings(
            "G54",
            findings,
            f"{len(text_sources)} candidate documents and modules scanned: no "
            "certification, production-readiness, layer-closure or self-acceptance "
            "claim is asserted anywhere",
            evidence,
        )

    # -- orchestration -----------------------------------------------------

    def run_runtime_phase(self) -> str:
        started = time.monotonic()
        self.phase_governance()

        if not drills_mod.pg_available():
            for gate_id in sorted(GATES):
                if gate_id in self.gates or gate_id in PACKAGE_PHASE_GATES:
                    continue
                self._record(
                    gate_id,
                    "BLOCKED",
                    "the PostgreSQL 16 toolchain required by the live drills is "
                    "unavailable in this environment",
                )
            return self._finish(started)

        session = DrillSession(self.root, self.artifact_zip, self.policy, self.instance_base)
        self.session = session
        try:
            if session.drill_j01():
                session.drill_j02()
                session.drill_j03_j04()
                session.drill_j05_j06()
                session.drill_j07()
                session.drill_j08_j11()
                session.drill_j12()
                session.drill_j13()
                session.drill_j14()
                session.drill_j15()
                session.drill_j16()
                session.drill_j17()
            else:
                for drill in sorted(drills_mod.DRILLS):
                    if drill != "J01":
                        session._blocked(drill, "the baseline deployment did not succeed")
            for phase in (
                self.phase_environment,
                self.phase_readiness,
                self.phase_recovery,
                self.phase_security,
                self.phase_voting,
                self.phase_evidence,
                self.phase_trial,
            ):
                try:
                    phase()
                except Exception as error:
                    # A phase that cannot complete leaves its gates BLOCKED —
                    # which blocks the seal — rather than aborting the run and
                    # leaving the runtime standing.
                    print(
                        f"[  PHASE-BLOCKED] {phase.__name__}: {error!r}"[:300],
                        flush=True,
                    )
                    self.phase_errors.append(f"{phase.__name__}: {error!r}"[:300])
        finally:
            session.stop()
        self.phase_regression()
        self.phase_authority()
        return self._finish(started)

    def _finish(self, started: float) -> str:
        for gate_id in sorted(GATES):
            if gate_id in self.gates or gate_id in PACKAGE_PHASE_GATES:
                continue
            detail = "gate did not execute in this run"
            if self.phase_errors:
                detail += f"; phase failures: {self.phase_errors[0]}"
            self._record(gate_id, "BLOCKED", detail)
        gates = [self.gates[key] for key in sorted(self.gates)]
        counted = {
            verdict: sum(1 for gate in gates if gate["result"] == verdict) for verdict in VERDICTS
        }
        summary = {
            **{key.lower(): value for key, value in counted.items()},
            "executed": len(gates),
            "governed_total": len(GATES),
            "package_phase_pending": list(PACKAGE_PHASE_GATES),
            "all_runtime_passed": counted["PASS"] == len(gates),
        }
        drills_document = (
            self.session.as_document()
            if self.session is not None
            else {"drills": [], "summary": {}}
        )
        accounting = [
            finding.describe()
            for finding in evaluators.check_gate_accounting(
                gates, len(GATES) - len(PACKAGE_PHASE_GATES), "runtime-phase"
            )
        ]
        self._emit(
            "e2e_drill_report.json",
            {
                "note": "The 18 governed drills, executed live. PREVIEW RUNTIME ONLY.",
                **drills_document,
            },
        )
        self._emit(
            "gate_report.json",
            {
                "note": "Runtime-phase gate report. G53 is executed by the package "
                "phase against the final archive bytes and merged there. This "
                "record is a developer pre-seal statement, never an acceptance.",
                "gates": gates,
                "summary": summary,
                "accounting_findings": accounting,
                "duration_seconds": round(time.monotonic() - started, 1),
                "freshness_recheck": [
                    finding.describe()
                    for finding in governance.check_freshness(
                        self.root, self.reconciliation.get("target_authority", {})
                    )
                ],
                "blockers": [
                    f"{gate['id']}: {gate['detail']}"
                    for gate in gates
                    if gate["result"] in {"FAIL", "BLOCKED"}
                ],
            },
        )
        verdict = "RUNTIME_PHASE_PASS" if summary["all_runtime_passed"] else "FAIL"
        print(f"\nINFRA04 runtime-phase gates: {counted} verdict={verdict}", flush=True)
        print(
            f"drills: {drills_document.get('summary')}",
            flush=True,
        )
        return verdict


PREDECESSOR_INFRA02_SHA = "d91fa6db81126765c0e26bf285fff2f974464544b7fa6299b6d069a25d1ff72c"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="scripts.infra04.gates")
    parser.add_argument("--root", default=".")
    parser.add_argument("--artifact", required=True, help="exact accepted INFRA-02 candidate ZIP")
    parser.add_argument("--instance-base", default=None)
    args = parser.parse_args(argv)
    runner = GateRunner(
        Path(args.root).resolve(),
        Path(args.artifact).resolve(),
        Path(args.instance_base).resolve() if args.instance_base else None,
    )
    verdict = runner.run_runtime_phase()
    return 0 if verdict == "RUNTIME_PHASE_PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
